### ISSUE TITLE
System.IO.IOException: No space left on device 

### ISSUE THREAD

**Issue by yasali** [actions/runner-images#10552]
### Description

```

build-and-testSystem.IO.IOException: No space left on device : '/Users/runner/runners/2.319.1/_diag/Worker_20240904-142056-utc.log' Unhandled exception. System.IO.IOException: No space left on device : '/Users/runner/runners/2.319.1/_diag/Worker_20240904-142056-utc.log'    at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)    at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()    at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)    at System.Diagnostics.TextWriterTraceListener.Flush()    at System.Diagnostics.TraceSource.Flush()    at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)    at GitHub.Runner.Common.TraceManager.Dispose()    at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)    at GitHub.Runner.Common.HostContext.Dispose()    at GitHub.Runner.Worker.Program.Main(String[] args)    at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)    at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()    at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)    at System.Diagnostics.TextWriterTraceListener.Flush()    at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)    at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)    at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)    at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)    at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args) System.IO.IOException: No space left on device : '/Users/runner/runners/2.319.1/_diag/Worker_20240904-142056-utc.log'    at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)    at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()    at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)    at System.Diagnostics.TextWriterTraceListener.Flush()    at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)    at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)    at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)    at GitHub.Runner.Common.Tracing.Error(Exception exception)    at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)Show less
--
build-and-testYou are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 56 MB

[build-and-test](https://github.com/nentgroup/viaplay-ios/actions/runs/10703619125/job/29674605734)
System.IO.IOException: No space left on device : '/Users/runner/runners/2.319.1/_diag/Worker_20240904-142056-utc.log'
Unhandled exception. System.IO.IOException: No space left on device : '/Users/runner/runners/2.319.1/_diag/Worker_20240904-142056-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device : '/Users/runner/runners/2.319.1/_diag/Worker_20240904-142056-utc.log'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
[build-and-test](https://github.com/nentgroup/viaplay-ios/actions/runs/10703619125/job/29674605734#step:1:38)
You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 56 MB
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

For the last 5 days we have been experiencing this No space left on the device error on macOS14 large image. We have tried to cleaning up the disk space manually but it did not help. 
name: Clean up disk space (iOS unit tests)

on: push

jobs:
  free-disk-space:
    runs-on: macos-14-xlarge
    steps:
      - name: Calculate initial disk space
        run: df -h

      - name: Clean Xcode derived data and caches
        run: |
          sudo rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Delete unnecessary simulator files
        run: |
          sudo rm -rf ~/Library/Developer/CoreSimulator/Caches/*
      - name: Clean up iOS DeviceSupport files
        run: |
          sudo rm -rf ~/Library/Developer/Xcode/iOS\ DeviceSupport/*
      - name: Check final disk space
        run: df -h
        
Any help is highly appreciated.

### Is it regression?

no

### Expected behavior

It should build without any issues.

### Actual behavior

Build fails with No space error

### Repro steps

All unit tests jobs are failing for example like below,

name: "iOS Unit testing"
on:
  pull_request:    
env:
  FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60
  FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 10
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-test:
    runs-on: macos-14-xlarge
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - uses: ./.github/setup
    - name: Setup timezone
      run: sudo systemsetup -settimezone Europe/Stockholm
    - uses: ./.github/unit-test
      with:
        environment: ios

**Comment by lilidotshi** [comment]
We are also periodically running into this issue. Is it possible to do some cleanup of the runners? I see in macos-14, there are 8 instances of Xcode installed, which must be taking up quite a bit of space off the runners.

**Comment by dakrawczyk** [comment]
My team is also running into this and have not found any solution. 

`You are running out of disk space. The runner will stop working when the machine runs out of disk space.`

We've gone through all steps we can find to clear caches, looking for help with how to confirm what is taking up all the available space.

Here is `df -h` from our  `runs-on: macos-latest-xlarge`


```
Filesystem        Size    Used   Avail Capacity iused ifree %iused  Mounted on
/dev/disk3s1s1   295Gi   9.6Gi    18Gi    36%    404k  185M    0%   /
devfs            347Ki   347Ki     0Bi   100%    1.2k     0  100%   /dev
/dev/disk3s6     295Gi    20Ki    18Gi     1%       0  185M    0%   /System/Volumes/VM
/dev/disk3s2     295Gi   4.9Gi    18Gi    22%     153  185M    0%   /System/Volumes/Preboot
/dev/disk3s4     295Gi   288Ki    18Gi     1%      23  185M    0%   /System/Volumes/Update
/dev/disk1s2     500Mi    20Ki   495Mi     1%       0  5.1M    0%   /System/Volumes/xarts
/dev/disk1s1     500Mi    96Ki   495Mi     1%      20  5.1M    0%   /System/Volumes/iSCPreboot
/dev/disk1s3     500Mi   196Ki   495Mi     1%      17  5.1M    0%   /System/Volumes/Hardware
/dev/disk3s5     295Gi   261Gi    18Gi    94%    2.2M  185M    1%   /System/Volumes/Data
map auto_home      0Bi     0Bi     0Bi   100%       0     0     -   /System/Volumes/Data/home
/dev/disk5s1      16Gi    15Gi   471Mi    98%    498k  4.8M    9%   /Library/Developer/CoreSimulator/Volumes/iOS_21A342
/dev/disk7s1     8.5Gi   8.2Gi   251Mi    98%      13  2.6M    0%   /Library/Developer/CoreSimulator/Cryptex/Images/bundle/SimRuntimeBundle
/dev/disk9s1      18Gi    18Gi   471Mi    98%    438k  4.8M    8%   /Library/Developer/CoreSimulator/Volumes/iOS_22B5023e
/dev/disk11s1     15Gi    14Gi   480Mi    97%    184k  4.9M    4%   /Library/Developer/CoreSimulator/Volumes/xrOS_21N305
/dev/disk13s1     16Gi    16Gi   460Mi    98%    521k  4.7M   10%   /Library/Developer/CoreSimulator/Volumes/iOS_21E213
/dev/disk15s1    4.0Gi   3.9Gi   139Mi    97%      13  1.4M    0%   /Library/Developer/CoreSimulator/Cryptex/Images/bundle/SimRuntimeBundle
/dev/disk17s1    9.5Gi   9.2Gi   269Mi    98%    172k  2.8M    6%   /Library/Developer/CoreSimulator/Volumes/tvOS_22J5335e
/dev/disk19s1    3.9Gi   3.6Gi   259Mi    94%    289k  2.6M   10%   /Library/Developer/CoreSimulator/Volumes/watchOS_20T253
/dev/disk21s1     15Gi    14Gi   418Mi    98%    192k  4.3M    4%   /Library/Developer/CoreSimulator/Volumes/xrOS_21O5565d
/dev/disk23s1    8.1Gi   7.8Gi   239Mi    98%      13  2.4M    0%   /Library/Developer/CoreSimulator/Cryptex/Images/bundle/SimRuntimeBundle
/dev/disk25s1     16Gi    16Gi   415Mi    98%    174k  4.2M    4%   /Library/Developer/CoreSimulator/Volumes/xrOS_22N5297g
/dev/disk27s1    4.1Gi   3.9Gi   142Mi    97%      13  1.5M    0%   /Library/Developer/CoreSimulator/Cryptex/Images/bundle/SimRuntimeBundle
/dev/disk29s1    9.8Gi   9.5Gi   284Mi    98%    262k  2.9M    8%   /Library/Developer/CoreSimulator/Volumes/watchOS_22R5328f
/dev/disk31s1    7.9Gi   7.6Gi   236Mi    98%      13  2.4M    0%   /Library/Developer/CoreSimulator/Cryptex/Images/bundle/SimRuntimeBundle
/dev/disk33s1     18Gi    17Gi   453Mi    98%    438k  4.6M    9%   /Library/Developer/CoreSimulator/Volumes/iOS_22A5346a
/dev/disk35s1    8.5Gi   8.2Gi   257Mi    98%    216k  2.6M    8%   /Library/Developer/CoreSimulator/Volumes/tvOS_21K364
/dev/disk37s1     16Gi    16Gi   467Mi    98%    507k  4.8M   10%   /Library/Developer/CoreSimulator/Volumes/iOS_21C62
/dev/disk39s1    9.7Gi   9.4Gi   300Mi    97%    341k  3.1M   10%   /Library/Developer/CoreSimulator/Volumes/watchOS_21T575
/dev/disk41s1    4.0Gi   3.9Gi   139Mi    97%      13  1.4M    0%   /Library/Developer/CoreSimulator/Cryptex/Images/bundle/SimRuntimeBundle
/dev/disk43s1    9.4Gi   9.1Gi   268Mi    98%    172k  2.7M    6%   /Library/Developer/CoreSimulator/Volumes/tvOS_22J5352a
/dev/disk45s1    8.0Gi   7.8Gi   240Mi    98%      13  2.5M    0%   /Library/Developer/CoreSimulator/Cryptex/Images/bundle/SimRuntimeBundle
/dev/disk47s1     16Gi    16Gi   416Mi    98%    174k  4.3M    4%   /Library/Developer/CoreSimulator/Volumes/xrOS_22N5314a
/dev/disk49s1    8.7Gi   8.4Gi   283Mi    97%    222k  2.9M    7%   /Library/Developer/CoreSimulator/Volumes/tvOS_21L224
/dev/disk51s1    8.7Gi   8.4Gi   284Mi    97%    223k  2.9M    7%   /Library/Developer/CoreSimulator/Volumes/tvOS_21L569
/dev/disk53s1    4.1Gi   3.9Gi   143Mi    97%      13  1.5M    0%   /Library/Developer/CoreSimulator/Cryptex/Images/bundle/SimRuntimeBundle
/dev/disk55s1    9.8Gi   9.5Gi   282Mi    98%    262k  2.9M    8%   /Library/Developer/CoreSimulator/Volumes/watchOS_22R5346a
/dev/disk57s1    9.7Gi   9.3Gi   305Mi    97%    340k  3.1M   10%   /Library/Developer/CoreSimulator/Volumes/watchOS_21T214
/dev/disk59s1    3.7Gi   3.4Gi   344Mi    91%    182k  3.5M    5%   /Library/Developer/CoreSimulator/Volumes/tvOS_20L494
/dev/disk61s1    4.0Gi   3.6Gi   375Mi    91%    212k  3.8M    5%   /Library/Developer/CoreSimulator/Volumes/tvOS_21J353
/dev/disk63s1     16Gi    16Gi   469Mi    98%    524k  4.8M   10%   /Library/Developer/CoreSimulator/Volumes/iOS_21F79
/dev/disk65s1    4.3Gi   4.0Gi   279Mi    94%    328k  2.9M   10%   /Library/Developer/CoreSimulator/Volumes/watchOS_21R355
/dev/disk67s1     15Gi    14Gi   414Mi    98%    192k  4.2M    4%   /Library/Developer/CoreSimulator/Volumes/xrOS_21O209
/dev/disk69s1    9.5Gi   9.2Gi   279Mi    98%    332k  2.9M   10%   /Library/Developer/CoreSimulator/Volumes/watchOS_21S364
```

**Comment by susmitamane** [comment]
Hi @yasali 

we are looking into it. will keep you posted.

**Comment by erik-bershel** [comment]
Hey there!

Initial issue placed here: https://github.com/actions/runner-images/issues/10511
I am closing this item as a clone.
