### ISSUE TITLE
Chromedriver installation issue during npm install

### ISSUE THREAD

**Issue by christopherjanzen** [actions/runner-images#10582]
### Description

Since the last week, during a Github Action that runs on ubuntu-latest, npm install is failing. We have not changed the action script or made any other changes to the npm packages. Here is a printout of the context and error:
```
> appium-chromedriver@4.26.2 postinstall /home/runner/work/sfra/sfra/storefront-reference-architecture-master/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js
[16:19:33] [Chromedriver Install] Installing Chromedriver version '86.0.4240.22' for platform 'linux' and architecture '64'
[16:19:33] [Chromedriver Install] Opening temp file to write 'chromedriver_linux64' to...
[16:19:33] [Chromedriver Install] Opened temp file '/tmp/202489-2027-ui2zcp.ugoz/chromedriver_linux64.zip'
[16:19:33] [Chromedriver Install] Downloading https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_linux64.zip to '/tmp/202489-2027-ui2zcp.ugoz/chromedriver_linux64.zip'
dbug Support https://chromedriver.storage.googleapis.com/86.0.4240.22/chromedriver_linux64.zip (5.20 MB) has been downloaded to '/tmp/202489-2027-ui2zcp.ugoz/chromedriver_linux64.zip' in 0.146s
[16:19:33] [Chromedriver Install] Extracting /tmp/202489-2027-ui2zcp.ugoz/chromedriver_linux64.zip to /tmp/202489-2027-ui2zcp.ugoz/chromedriver_linux64
[16:19:34] [Chromedriver Install] Creating /home/runner/work/sfra/sfra/storefront-reference-architecture-master/node_modules/appium/node_modules/appium-chromedriver/chromedriver/linux...
[16:19:34] [Chromedriver Install] Copying unzipped binary, reading from /tmp/202489-2027-ui2zcp.ugoz/chromedriver_linux64/chromedriver...
[16:19:34] [Chromedriver Install] Writing to /home/runner/work/sfra/sfra/storefront-reference-architecture-master/node_modules/appium/node_modules/appium-chromedriver/chromedriver/linux/chromedriver_64...
[16:19:34] [Chromedriver Install] /home/runner/work/sfra/sfra/storefront-reference-architecture-master/node_modules/appium/node_modules/appium-chromedriver/chromedriver/linux/chromedriver_64 successfully put in place
> core-js@2.6.12 postinstall /home/runner/work/sfra/sfra/storefront-reference-architecture-master/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"
> sauce-connect-launcher-update@1.3.2 postinstall /home/runner/work/sfra/sfra/storefront-reference-architecture-master/node_modules/sauce-connect-launcher-update
> node scripts/install.js || nodejs scripts/install.js
> sauce-connect-launcher@1.3.2 postinstall /home/runner/work/sfra/sfra/storefront-reference-architecture-master/node_modules/sauce-connect-launcher
> node scripts/install.js || nodejs scripts/install.js
> sauce-connect-launcher@1.2.7 postinstall /home/runner/work/sfra/sfra/storefront-reference-architecture-master/node_modules/wdio-sauce-service/node_modules/sauce-connect-launcher
> node scripts/install.js || nodejs scripts/install.js
> puppeteer@23.3.0 postinstall /home/runner/work/sfra/sfra/storefront-reference-architecture-master/node_modules/puppeteer
> node install.mjs
Skipping browser installation because the Puppeteer build is not available. Run `npm install` again after you have re-built Puppeteer.
> appium-chromedriver@4.28.0 postinstall /home/runner/work/sfra/sfra/storefront-reference-architecture-master/node_modules/appium-chromedriver
> node install-npm.js
[16:19:35] Error installing Chromedriver: DOMParser.parseFromString: the provided mimeType "undefined" is not valid.
[16:19:35] TypeError: DOMParser.parseFromString: the provided mimeType "undefined" is not valid.
    at DOMParser.parseFromString (/home/runner/work/sfra/sfra/storefront-reference-architecture-master/node_modules/@xmldom/xmldom/lib/dom-parser.js:215:9)
    at ChromedriverStorageClient.retrieveMapping (/home/runner/work/sfra/sfra/storefront-reference-architecture-master/node_modules/appium-chromedriver/lib/storage-client.js:210:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at ChromedriverStorageClient.syncDrivers (/home/runner/work/sfra/sfra/storefront-reference-architecture-master/node_modules/appium-chromedriver/lib/storage-client.js:406:7)
    at install (/home/runner/work/sfra/sfra/storefront-reference-architecture-master/node_modules/appium-chromedriver/lib/install.js:33:3)
    at Object.doInstall (/home/runner/work/sfra/sfra/storefront-reference-architecture-master/node_modules/appium-chromedriver/lib/install.js:40:3)
[16:19:35] Downloading Chromedriver can be skipped by using the '--chromedriver-skip-install' flag or setting the 'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.
npm WARN notsup Unsupported engine for puppeteer@23.3.0: wanted: {"node":">=18"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: puppeteer@23.3.0
npm WARN notsup Unsupported engine for puppeteer-core@23.3.0: wanted: {"node":">=18"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: puppeteer-core@23.3.0
npm WARN notsup Unsupported engine for @puppeteer/browsers@2.4.0: wanted: {"node":">=18"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @puppeteer/browsers@2.4.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@4.28.0 postinstall: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@4.28.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2024-09-09T16_19_38_309Z-debug.log
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240901.1.0

### Is it regression?

20240825.1.0

### Expected behavior

npm install is successful

### Actual behavior

npm install fails

### Repro steps

Perform npm install using github action using ubuntu-latest or ubuntu-20.04 with the attached package.json
[package.json](https://github.com/user-attachments/files/16933499/package.json)

**Comment by hemanthmanga** [comment]
Hi @christopherjanzen Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by christopherjanzen** [comment]
I'm not sure exactly what has changed but even on my local machine, I cannot successfully run `npm install` with a fresh copy of my repository. I've updated the appium package which has resolved the issue.
