### ISSUE TITLE
Xcode 16 - upload_to_testflight failed

### ISSUE THREAD

**Issue by salvatoreboemia** [actions/runner-images#10675]
### Description

Hi I got this error only when I use Xcode 16 on GitHub. 

Locally I uploaded the build also using fastlane with no error. Only with my GitHub Action I got the error and only on this branch with code 16. all others branch works fine (with xcode 15.4)

### Issue Description
upload to test flight failed

### Error
```
[11:38:30]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Publish to Test Flight Error
    https://github.com/fastlane/fastlane/issues/18062 [closed] 5 💬
    24 Apr 2021

➡️  Pilot - undefined method `strip' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/15204 [closed] 12 💬
    26 Nov 2019

➡️  some wrong happen when I use fastlane to upload an ipa file
    https://github.com/fastlane/fastlane/issues/14272 [closed] 6 💬
    11 Jun 2019

and 2 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60start_with%3F%27%20for%20nil&type=Issues&utf8=✓
/opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:685:in `initialize': \e[31m[!] undefined method `start_with?' for nil:NilClass\e[0m (NoMethodError)
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/pilot/lib/pilot/build_manager.rb:412:in `new'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/pilot/lib/pilot/build_manager.rb:412:in `transporter_for_selected_team'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/pilot/lib/pilot/build_manager.rb:49:in `upload'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:276:in `block (2 levels) in parsing_binding'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:685:in `initialize': undefined method `start_with?' for nil:NilClass (NoMethodError)
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/pilot/lib/pilot/build_manager.rb:412:in `new'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/pilot/lib/pilot/build_manager.rb:412:in `transporter_for_selected_team'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/pilot/lib/pilot/build_manager.rb:49:in `upload'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:276:in `block (2 levels) in parsing_binding'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/bin/fastlane:23:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/fastlane:25:in `<main>
```

### My lane
```
lane :uploadTF do |options|
    upload_to_testflight(
      api_key_path: "myJson",
      ipa: "./DerivedData/Build/MyApp",
      changelog: "log",
      groups: "team",
      distribute_external: true,
      skip_waiting_for_build_processing: false
    )
  end
```

Only on a specific branch of Xcode 16, where I use in the GitHub Action `Xcode_16.app.`

And I notice that in the log it talks about pilot.

Archive works, only the upload fails

What's wrong?

Thanks

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macOS 14 xl

### Is it regression?

work with xcode 15.4

### Expected behavior

upload to test flight works fine

### Actual behavior

upload to test flight don't work

### Repro steps

try to upload with fastlane a buil to test flight using GitHub Action

**Comment by sureshe456** [comment]
Hi @salvatoreboemia, We will look into this issue and keep you updated.

**Comment by salvatoreboemia** [comment]
> Hi @salvatoreboemia, We will look into this issue and keep you updated.

thanks

just a note 

I deleted all the Xcode before executing, (due to space availability on runners) and I think you are still using the command line tool 15.4 also if Xcode_16.app is selected  (this is why the branch using code 15.4 still working fine)

```
Current Xcode path BEFORE delete:
/Applications/Xcode_15.4.app/Contents/Developer
 
Current Xcode path AFTER delete:
/Library/Developer/CommandLineTools
```

**Comment by erik-bershel** [comment]
The image has several versions of Xcode installed and it is necessary to change the default version if you want to use a different one from the pre-configured one. You can do it yourself, or you can use an action, for example: [maxim-lobanov/setup-xcode](https://github.com/maxim-lobanov/setup-xcode)

Since the problem was related to the configuration of a specific build, I am closing the issue - feel free to open new ones in case of other problems.
