### ISSUE TITLE
Git credential-manager FAILS

### ISSUE THREAD

**Issue by rolandmosimann** [actions/runner-images#11176]
### Description

Running `git credential-manager diagnose` on the latest image fails.

Runner Image
  Image: windows-2022
  Version: 20241211.1.0

Credential-manager version: 2.6.0+3c28096588f549cb46f36b552390514356830abe

Diagnosis output:
```

Running diagnostics...

  >>>>  Environment[ OK ] Environment
  >>>>  File system[ OK ] File system
  >>>>  Networking[ OK ] Networking
  >>>>  Git[ OK ] Git
  >>>>  Credential storage[FAIL] Credential storage

    [!] Encountered an exception [!]
    System.Exception: Unable to persist credentials with the 'wincredman' credential store.
    
    See https://aka.ms/gcm/credstores for more information.
    
       at GitCredentialManager.CredentialStore.ValidateWindowsCredentialManager()
    
       at GitCredentialManager.CredentialStore.EnsureBackingStore()
    
       at GitCredentialManager.CredentialStore.Remove(String service, String account)
    
       at GitCredentialManager.Diagnostics.CredentialStoreDiagnostic.RunInternalAsync(StringBuilder log, IList`1 additionalFiles)
    
       at GitCredentialManager.Diagnostics.Diagnostic.<RunAsync>d__6.MoveNext()

    [*] Diagnostic test log [*]
    ICredentialStore instance is of type: CredentialStore
    
    Writing test credential...Deleting test credential...

  >>>>  Microsoft authentication (AAD/MSA)[ OK ] Microsoft authentication (AAD/MSA)
  >>>>  GitHub API[ OK ] GitHub API

Diagnostic summary: 6 passed, 0 skipped, 1 failed.
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Runner Image
  Image: windows-2022
  Version: 20241211.1.0

### Is it regression?

Version: 20241202.1.0

### Expected behavior

NO Failure.

### Actual behavior

Credential storage[FAIL] Credential storage

### Repro steps

run workflow on latest image:

    - id: windows-set-credential-store
      if: runner.os == 'Windows'
      shell: bash
      run: |
          git credential-manager --version
          git credential-manager diagnose

Possible workaround

    - id: windows-set-credential-store
      if: runner.os == 'Windows'
      shell: bash
      run: |
        git config --global credential.credentialStore dpapi

**Comment by subir0071** [comment]
This should is fixed now.
Please revert if you are still facing the issue.
