### ISSUE TITLE
XamarinTelemetry build issue with the current Visual Studio version

### ISSUE THREAD

**Issue by kevcrooks** [actions/runner-images#6101]
### Description

The current build agents are using Visual Studio 17.3.32804.467 (https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md)

However this version has an issue which will cause Xamarin builds to sometimes fail with the following error:

```
##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Xamarin.Sdk.targets(138,9): Error MSB4018: The "XamarinTelemetry" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Microsoft.VisualStudio.Telemetry.TelemetrySessionSettings.GetFaultEventBucketFilterJson(List`1 bucketFilters)
   at Microsoft.VisualStudio.Telemetry.TelemetrySessionSettings.ToString()
   at Microsoft.VisualStudio.Telemetry.TelemetrySession.SerializeSettings()
   at Xamarin.Common.Tasks.Telemetry.GetSession(IBuildEngine4 buildEngine, String vsTelemetrySession) in D:\a\_work\1\s\src\MSBuild\Xamarin.Common.Tasks\Telemetry.cs:line 62
   at Xamarin.Common.Tasks.XamarinTelemetry.Execute() in D:\a\_work\1\s\src\MSBuild\Xamarin.Common.Tasks\XamarinTelemetry.cs:line 31
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

This has been fixed in the latest Visual Studio version:
17.3.1 (17.3.32811.315)

Can the agents be updated to use the newest Visual Studio version?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20220814.1

### Is it regression?

yes, this was ok prior to Visual Studio 17.3.0 I think

### Expected behavior

Build should always succeed without the XamarinTelemetry error

### Actual behavior

Build will occasionally fail (but not always)

### Repro steps

Build a Xamarin app using the 2022 Windows agent

**Comment by al-cheb** [comment]
Hello @kevcrooks.
We will take a look at it.

**Comment by kevcrooks** [comment]
Thank you, for reference, here's one of the associated VS bug reports, showing that the issue is fixed in the latest release, so would be good to get this on the build agents when possible: https://developercommunity.visualstudio.com/t/Unexpected-error-of-task-Xamarin-Teleme/10096527

**Comment by al-cheb** [comment]
The new image with VS 17.3.32811.315 has been deployed.
