### ISSUE TITLE
x86_64 Android 31 emulator launch fails on Macos latest runner

### ISSUE THREAD

**Issue by mpconte** [actions/runner-images#6252]
### Description

When trying to launch an Android emulator using a x86_64 system image, with google_apis target for Goodle API 31, the action appears to stall and not launch the emulator.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20220912.1

### Is it regression?

no

### Expected behavior

Successfully launch an Android emulator on the macos-latest runner

### Actual behavior

Log output of installing the required system image:

```
sdkmanager --install "system-images;android-31;google_apis;x86_64"
echo "no" | avdmanager --verbose create avd --force --name testAVD --abi google_apis/x86_64 --package 'system-images;android-31;google_apis;x86_64'
```

Log output of running the Android emulator:

```
Run $ANDROID_SDK_ROOT/emulator/emulator -avd testAVD
  $ANDROID_SDK_ROOT/emulator/emulator -avd testAVD
  shell: /bin/bash -e {0}
  env:
    JAVA_HOME: /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.4-101/x64/Contents/Home
    JAVA_HOME_17_X64: /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.4-101/x64/Contents/Home
    ANDROID_HOME: /Users/runner/Library/Android/sdk
    ANDROID_SDK_ROOT: /Users/runner/Library/Android/sdk
    GRADLE_BUILD_ACTION_SETUP_COMPLETED: true
    GRADLE_BUILD_ACTION_CACHE_RESTORED: true
INFO    | Android emulator version 31.3.10.0 (build_id 88079[2](https://github.com/SensoftInc/kotlin_demo/actions/runs/3061926246/jobs/4942297456#step:9:2)7) (CL:N/A)
emulator: INFO: Found systemPath /Users/runner/Library/Android/sdk/system-images/android-[3](https://github.com/SensoftInc/kotlin_demo/actions/runs/3061926246/jobs/4942297456#step:9:3)1/google_apis/x86_6[4](https://github.com/SensoftInc/kotlin_demo/actions/runs/3061926246/jobs/4942297456#step:9:4)/
WARNING | unexpected system image feature string, emulator might not function correctly, please try updating the emulator.
WARNING | /etc/localtime does not point to zoneinfo-compatible timezone name
WARNING | Your GPU drivers may have a bug. Switching to software rendering.
WARNING | cannot add library /Users/runner/Library/Android/sdk/emulator/qemu/darwin-x86_64/lib64/vulkan/libvulkan.dylib: failed
INFO    | Duplicate loglines will be removed, if you wish to see each indiviudal line launch with the -log-nofilter flag.
INFO    | added library /Users/runner/Library/Android/sdk/emulator/lib64/vulkan/libvulkan.dylib
INFO    | configAndStartRenderer: setting vsync to 60 hz
INFO    | Sending adb public key [QAAAAHcn[5](https://github.com/SensoftInc/kotlin_demo/actions/runs/3061926246/jobs/4942297456#step:9:5)5S5HWRNwTvmBJOqmLORrKxpJreI3gw0zYFAHfdhjPB8eYy0Wh1T3JwmtNi8pNSm5DLKb0aD+QuYZEmi81eit2bGRqo9x3M8IlPjL7kckoKmDEgMR1Y9f28wuypL2rNlzrbctROvvHYPGhWoJU9CF8t52rHys[6](https://github.com/SensoftInc/kotlin_demo/actions/runs/3061926246/jobs/4942297456#step:9:6)kqICgfX4cTHdA5rVtqq04sqew4xm[7](https://github.com/SensoftInc/kotlin_demo/actions/runs/3061926246/jobs/4942297456#step:9:7)OUp1K+pzlSBdenjj[8](https://github.com/SensoftInc/kotlin_demo/actions/runs/3061926246/jobs/4942297456#step:9:8)R4XltrtJiwJ7+heQ[9](https://github.com/SensoftInc/kotlin_demo/actions/runs/3061926246/jobs/4942297456#step:9:9)HrBD8dTq1bAsTBzdz8/N0EDQcgNZB6Ou/cMWpsIR86M8aQcBRbKfxVVAOd1BqpdayMdW474D32KG58EjzEU8jYpr3g4OsYFx9hbQAJ2EPHY6DRJPZSSVKZ+eoO2UT2cWObByJqh6ruoyiQMgGEgUI9GAlhZyoF6CojXA5TqLewRvGOh3uwp6aOG13wvztGksh9KUs/HOysjwwzJUEylXLz4INRdHtxFM4OjWywdwr1ekkv8HqwcJ[12](https://github.com/SensoftInc/kotlin_demo/actions/runs/3061926246/jobs/4942297456#step:9:13)wIU7KQZj2rvNMsweHBnu+Fn0J60WVr2DUQQAFM0r+YZgbDm5C6JOSMDcUa3m1hlAgWrrs8WHK9EC/sYRdEpvOw/C+qYeRA2jcs6CyWpdrDa50ufSVBGhex+RS8UKNd9DLAcASR+N0C/cOwfJ5tHuqpzCBgRb5kDraYGIowKr927AuzezBESRB1htIlOAFhOMgWjdgcMQ42liRPfXYLJRZ2fpsHQEAAQA= runner@unknown]
INFO    | injectedQemuChannel!
INFO    | Informing listeners of injection.
INFO    | Rootcanal has  been activated.
WARNING | /etc/localtime does not point to zoneinfo-compatible timezone name
WARNING | *** No gRPC protection active, consider launching with the -grpc-use-jwt flag.***
INFO    | Started GRPC server at 127.0.0.1:8554, security: Local, auth: none
INFO    | Advertising in: /Users/runner/Library/Caches/TemporaryItems/avd/running/pid_4080.ini
INFO    | setDisplayConfigs w 320 h 640 dpiX 160 dpiY 160
WARNING | Failed to process .ini file /Users/runner/.android/emu-update-last-check.ini for reading.
WARNING | Failed to process .ini file /Users/runner/.android/emu-update-last-check.ini for reading.
INFO    | Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"

ERROR   | Unable to connect to adb daemon on port: 5037
2022-09-15 16:06:08.595 qemu-system-x86_64[4080:16794] [CAMetalLayer nextDrawable] returning nil because device is nil.
2022-09-15 16:06:08.682 qemu-system-x86_64[4080:16794] [CAMetalLayer nextDrawable] returning nil because device is nil.
2022-09-15 16:06:08.706 qemu-system-x86_64[4080:16794] [CAMetalLayer nextDrawable] returning nil because device is nil.
2022-09-15 16:06:08.709 qemu-system-x86_64[4080:16794] [CAMetalLayer nextDrawable] returning nil because device is nil.
2022-09-15 16:06:08.7[13](https://github.com/SensoftInc/kotlin_demo/actions/runs/3061926246/jobs/4942297456#step:9:14) qemu-system-x86_64[4080:16794] [CAMetalLayer nextDrawable] returning nil because device is nil.
2022-09-[15](https://github.com/SensoftInc/kotlin_demo/actions/runs/3061926246/jobs/4942297456#step:9:16) [16](https://github.com/SensoftInc/kotlin_demo/actions/runs/3061926246/jobs/4942297456#step:9:17):06:08.716 qemu-system-x86_64[[40](https://github.com/SensoftInc/kotlin_demo/actions/runs/3061926246/jobs/4942297456#step:9:41)80:16794] [CAMetalLayer nextDrawable] returning nil because device is nil.
```

### Repro steps

Sample workflow file:
```
name: Android CI

on:
  push:
    branches: [ "pinch_zoom" ]
  
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Create directory for jni libs
      run: mkdir app/libs && mkdir app/libs/arm64-v8a      

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Setup gradle
      uses: gradle/gradle-build-action@v2    
        
    - name: Create Android emulator
      run: |
        sdkmanager --install "system-images;android-31;google_apis;x86_64"
        echo "no" | avdmanager --verbose create avd --force --name testAVD --abi google_apis/x86_64 --package 'system-images;android-31;google_apis;x86_64'
        
    - name: Copy jar files to app folder
      run: gradle extractLibs

    - name: Launch Emulator
      run: | 
        $ANDROID_SDK_ROOT/emulator/emulator -avd testAVD
        
    - name: Run instrumentation tests
      run: |                
        gradle connectedAndroidTest --stacktrace
        
    - name: Build apk file
      run: gradle assembleRelease

    - name: Upload (unsigned) APK
      uses: actions/upload-artifact@v2.2.4
      with:
          name: kotlin_demo_apk
          path: ${{github.workspace}}/app/build/outputs/apk/release/app-release-unsigned.apk

```

**Comment by mikhailkoliada** [comment]
@mpconte Hello!

We will take a look.

**Comment by igorboskovic3** [comment]
CC: @dsame

**Comment by igorboskovic3** [comment]
Hi @mpconte can you check same issue [here](https://github.com/actions/runner-images/issues/6152) that we recently resolved and let us know results, thank you

**Comment by mpconte** [comment]
Hi @igorboskovic3 

So I tried to follow the steps in the linked issue. 

Currently when I run this step:

`echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-31;google_apis;x86_64"`

I get the following error:

```
2022-09-16T16:47:00.6835630Z ##[error]Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
2022-09-16T16:47:00.6849590Z 	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
2022-09-16T16:47:00.6850170Z 	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
2022-09-16T16:47:00.6850840Z 	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
2022-09-16T16:47:00.6851360Z 	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
2022-09-16T16:47:00.6851830Z 	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
2022-09-16T16:47:00.6852300Z Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
2022-09-16T16:47:00.6853070Z 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
2022-09-16T16:47:00.6853590Z 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
2022-09-16T16:47:00.6854050Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
2022-09-16T16:47:00.6854370Z 	... 5 more
2022-09-16T16:47:00.6897090Z ##[error]Process completed with exit code 1.
```

**Comment by mpconte** [comment]
@igorboskovic3 I managed to resolve my issue by removing the shell script to wait for the device to load following the **wait-for-device** command.

i.e:

`$ANDROID_HOME/platform-tools/adb wait-for-device `

instead of

`$ANDROID_HOME/platform-tools/adb wait-for-device  shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do echo "wait..."; sleep 1; done; input keyevent 82'
`

**Comment by ssrinivasKG** [comment]
I still believe the latest runner image does not have HAXM installed and running `emulator -accel-check` after installing Intel HaxM shows the following error output. 
`accel:
8
HAXM is not installed on this machine (/dev/HAX is missing).
accel`

Which is causing the emulator to be super slow since its unable to startup using hardware acceleration. Not sure if @mpconte you're facing a similar issue or you would once you get the emulator up and running

**Comment by mpconte** [comment]
My workflow didn't appear to have an issue with installing **intel-haxm**, although running `emulator -accel-check ` did indeed give me the same error output you said.

My (very simple) instrumentation test seems to pass, so I believe that everything is working fine on my end.

**Comment by igorboskovic3** [comment]
@mpconte can you try use this `brew install intel-haxm` before installation of emulator

**Comment by igorboskovic3** [comment]
@mpconte sorry, didnt saw your last comment

**Comment by igorboskovic3** [comment]
Ok i will close then this issue, thank you @mpconte and @ssrinivasKG

**Comment by GledsonLScruz** [comment]
Hi guys, I am with this problem right now, running on macOs Ventura, when i run an android emulator with a x86 image, it boots normally. But when I try a x86_64 image for example the upsideDownCake, it only show a black screen and the android studio still waiting for a device!

![Screenshot 2023-12-12 at 14 55 50](https://github.com/actions/runner-images/assets/86816795/64bfb354-d1d4-4b4e-a445-ebceedbdeac5)

**Comment by GledsonLScruz** [comment]
![image](https://github.com/actions/runner-images/assets/86816795/3300f3c5-917a-40fa-9f63-e9c4219c7de9)

this is the android studio log

**Comment by tremp-m** [comment]
@GledsonLScruz same problem

**Comment by alisonglima** [comment]
> Olá pessoal, estou com esse problema agora, rodando no macOs Ventura, quando executo um emulador de android com imagem x86, ele inicializa normalmente. Mas quando tento uma imagem x86_64, por exemplo, o upsideDownCake, ela só mostra uma tela preta e o Android Studio ainda está esperando por um dispositivo!
> 
> ![Captura de tela 12/12/2023 às 14 55 50](https://private-user-images.githubusercontent.com/86816795/289958500-64bfb354-d1d4-4b4e-a445-ebceedbdeac5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MjAwNDgsIm5iZiI6MTcwNDgxOTc0OCwicGF0aCI6Ii84NjgxNjc5NS8yODk5NTg1MDAtNjRiZmIzNTQtZDFkNC00YjRlLWE0NDUtZWJjZWVkYmRlYWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE3MDIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlOGNiYzViOWYwMDgzMTU3ODE5YTFkYzg1YzFkNjY4NGRjZjIxNDA3M2JhZjlhZGFjY2UzNWIwNDYxN2M0ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CifC_T_dvTpQBbTBT5ydMZskxTrQdNSabUEpep4cu7E)

Também tenho o mesmo problema =/

**Comment by arslc** [comment]
@GledsonLScruz look at this fix: https://www.reddit.com/r/hackintosh/comments/183oe42/solved_run_android_emulator_in_intel_hackintosh/

If u're using hackintosh it's helpful to u

**Comment by neuberfran** [comment]
@GledsonLScruz dO u solve it?
