### ISSUE TITLE
Ansible Galaxy : bootstrap error

### ISSUE THREAD

**Issue by nlamirault** [actions/runner-images#6733]
### Description

Hi,
I try to execute an Ansible playbook in `windows-latest` runner image, and it fails with this error: 

```
2022-12-08T15:40:38.0806349Z Requested labels: windows-latest
2022-12-08T15:40:38.0806390Z Job defined at: nlamirault/divona/.github/workflows/setup-windows.yml@refs/pull/60/merge
2022-12-08T15:40:38.0806415Z Waiting for a runner to pick up this job...
2022-12-08T15:40:38.7752826Z Job is waiting for a hosted runner to come online.
2022-12-08T15:41:08.1250396Z Job is about to start running on the hosted runner: GitHub Actions 8 (hosted)
2022-12-08T15:41:13.3007889Z Current runner version: '2.299.1'
2022-12-08T15:41:13.3033088Z ##[group]Operating System
2022-12-08T15:41:13.3033626Z Microsoft Windows Server 2022
2022-12-08T15:41:13.3033921Z 10.0.20348
2022-12-08T15:41:13.3034200Z Datacenter
2022-12-08T15:41:13.3034423Z ##[endgroup]
2022-12-08T15:41:13.3034699Z ##[group]Runner Image
2022-12-08T15:41:13.3035000Z Image: windows-2022
2022-12-08T15:41:13.3035239Z Version: 20221204.3
2022-12-08T15:41:13.3035698Z Included Software: https://github.com/actions/runner-images/blob/win22/20221204.3/images/win/Windows2022-Readme.md
2022-12-08T15:41:13.3036266Z Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20221204.3
2022-12-08T15:41:13.3036616Z ##[endgroup]
2022-12-08T15:41:13.3036914Z ##[group]Runner Image Provisioner
2022-12-08T15:41:13.3037233Z 2.0.91.1
2022-12-08T15:41:13.3037473Z ##[endgroup]
2022-12-08T15:41:13.3038386Z ##[group]GITHUB_TOKEN Permissions
2022-12-08T15:41:13.3038933Z Actions: write
2022-12-08T15:41:13.3039394Z Checks: write
2022-12-08T15:41:13.3039694Z Contents: write
2022-12-08T15:41:13.3039975Z Deployments: write
2022-12-08T15:41:13.3040259Z Discussions: write
2022-12-08T15:41:13.3040511Z Issues: write
2022-12-08T15:41:13.3040791Z Metadata: read
2022-12-08T15:41:13.3041063Z Packages: write
2022-12-08T15:41:13.3041290Z Pages: write
2022-12-08T15:41:13.3041587Z PullRequests: write
2022-12-08T15:41:13.3041921Z RepositoryProjects: write
2022-12-08T15:41:13.3042190Z SecurityEvents: write
2022-12-08T15:41:13.3042504Z Statuses: write
2022-12-08T15:41:13.3042806Z ##[endgroup]
2022-12-08T15:41:13.3046329Z Secret source: Actions
2022-12-08T15:41:13.3046798Z Prepare workflow directory
2022-12-08T15:41:13.4017606Z Prepare all required actions
2022-12-08T15:41:13.4201581Z Getting action download info
2022-12-08T15:41:13.7974007Z Download action repository 'actions/checkout@v3.1.0' (SHA:93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8)
2022-12-08T15:41:14.5044974Z Download action repository 'actions/setup-python@v4.2.0' (SHA:b55428b1882923874294fa556849718a1d7f2ca5)
2022-12-08T15:41:15.6939239Z Download action repository 'dawidd6/action-ansible-playbook@v2.6.1' (SHA:5d970176ea4bfd99a3f5004d48e293fe0994eda1)
2022-12-08T15:41:16.8759458Z ##[group]Run actions/checkout@v3.1.0
2022-12-08T15:41:16.8759787Z with:
2022-12-08T15:41:16.8759982Z   repository: nlamirault/divona
2022-12-08T15:41:16.8760399Z   token: ***
2022-12-08T15:41:16.8760575Z   ssh-strict: true
2022-12-08T15:41:16.8760793Z   persist-credentials: true
2022-12-08T15:41:16.8760988Z   clean: true
2022-12-08T15:41:16.8761166Z   fetch-depth: 1
2022-12-08T15:41:16.8761327Z   lfs: false
2022-12-08T15:41:16.8761492Z   submodules: false
2022-12-08T15:41:16.8761694Z   set-safe-directory: true
2022-12-08T15:41:16.8761882Z ##[endgroup]
2022-12-08T15:41:22.3519383Z Syncing repository: nlamirault/divona
2022-12-08T15:41:22.3671007Z ##[group]Getting Git version info
2022-12-08T15:41:22.3671747Z Working directory is 'D:\a\divona\divona'
2022-12-08T15:41:22.3964412Z [command]"C:\Program Files\Git\bin\git.exe" version
2022-12-08T15:41:22.8664128Z git version 2.38.1.windows.1
2022-12-08T15:41:22.8704604Z ##[endgroup]
2022-12-08T15:41:22.8728508Z Temporarily overriding HOME='D:\a\_temp\8af194c1-5300-4d90-9468-0625779ba9b2' before making global git config changes
2022-12-08T15:41:22.8733102Z Adding repository directory to the temporary git global config as a safe directory
2022-12-08T15:41:22.8740628Z [command]"C:\Program Files\Git\bin\git.exe" config --global --add safe.directory D:\a\divona\divona
2022-12-08T15:41:22.9396087Z Deleting the contents of 'D:\a\divona\divona'
2022-12-08T15:41:22.9404475Z ##[group]Initializing the repository
2022-12-08T15:41:22.9418178Z [command]"C:\Program Files\Git\bin\git.exe" init D:\a\divona\divona
2022-12-08T15:41:23.0098513Z Initialized empty Git repository in D:/a/divona/divona/.git/
2022-12-08T15:41:23.0135304Z [command]"C:\Program Files\Git\bin\git.exe" remote add origin https://github.com/nlamirault/divona
2022-12-08T15:41:23.0656221Z ##[endgroup]
2022-12-08T15:41:23.0657017Z ##[group]Disabling automatic garbage collection
2022-12-08T15:41:23.0678841Z [command]"C:\Program Files\Git\bin\git.exe" config --local gc.auto 0
2022-12-08T15:41:23.0910468Z ##[endgroup]
2022-12-08T15:41:23.0912594Z ##[group]Setting up auth
2022-12-08T15:41:23.0940175Z [command]"C:\Program Files\Git\bin\git.exe" config --local --name-only --get-regexp core\.sshCommand
2022-12-08T15:41:23.1153709Z [command]"C:\Program Files\Git\bin\git.exe" submodule foreach --recursive "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2022-12-08T15:41:25.0364500Z [command]"C:\Program Files\Git\bin\git.exe" config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2022-12-08T15:41:25.0596873Z [command]"C:\Program Files\Git\bin\git.exe" submodule foreach --recursive "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2022-12-08T15:41:25.4942231Z [command]"C:\Program Files\Git\bin\git.exe" config --local http.https://github.com/.extraheader "AUTHORIZATION: basic ***"
2022-12-08T15:41:25.5169355Z ##[endgroup]
2022-12-08T15:41:25.5169768Z ##[group]Fetching the repository
2022-12-08T15:41:25.5199289Z [command]"C:\Program Files\Git\bin\git.exe" -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +a735d8d7fa5984e172179e20341d06d62260df6d:refs/remotes/pull/60/merge
2022-12-08T15:41:26.9601049Z remote: Enumerating objects: 59, done.        
2022-12-08T15:41:26.9601456Z remote: Counting objects:   1% (1/59)        
2022-12-08T15:41:26.9601769Z remote: Counting objects:   3% (2/59)        
2022-12-08T15:41:26.9602062Z remote: Counting objects:   5% (3/59)        
2022-12-08T15:41:26.9602346Z remote: Counting objects:   6% (4/59)        
2022-12-08T15:41:26.9602615Z remote: Counting objects:   8% (5/59)        
2022-12-08T15:41:26.9604194Z remote: Counting objects:  10% (6/59)        
2022-12-08T15:41:26.9604611Z remote: Counting objects:  11% (7/59)        
2022-12-08T15:41:26.9606248Z remote: Counting objects:  13% (8/59)        
2022-12-08T15:41:26.9606637Z remote: Counting objects:  15% (9/59)        
2022-12-08T15:41:26.9606932Z remote: Counting objects:  16% (10/59)        
2022-12-08T15:41:26.9607292Z remote: Counting objects:  18% (11/59)        
2022-12-08T15:41:26.9607527Z remote: Counting objects:  20% (12/59)        
2022-12-08T15:41:26.9607822Z remote: Counting objects:  22% (13/59)        
2022-12-08T15:41:26.9608117Z remote: Counting objects:  23% (14/59)        
2022-12-08T15:41:26.9608394Z remote: Counting objects:  25% (15/59)        
2022-12-08T15:41:26.9608681Z remote: Counting objects:  27% (16/59)        
2022-12-08T15:41:26.9608962Z remote: Counting objects:  28% (17/59)        
2022-12-08T15:41:26.9609238Z remote: Counting objects:  30% (18/59)        
2022-12-08T15:41:26.9609515Z remote: Counting objects:  32% (19/59)        
2022-12-08T15:41:26.9609796Z remote: Counting objects:  33% (20/59)        
2022-12-08T15:41:26.9610074Z remote: Counting objects:  35% (21/59)        
2022-12-08T15:41:26.9610349Z remote: Counting objects:  37% (22/59)        
2022-12-08T15:41:26.9610624Z remote: Counting objects:  38% (23/59)        
2022-12-08T15:41:26.9610894Z remote: Counting objects:  40% (24/59)        
2022-12-08T15:41:26.9611230Z remote: Counting objects:  42% (25/59)        
2022-12-08T15:41:26.9611505Z remote: Counting objects:  44% (26/59)        
2022-12-08T15:41:26.9611774Z remote: Counting objects:  45% (27/59)        
2022-12-08T15:41:26.9612053Z remote: Counting objects:  47% (28/59)        
2022-12-08T15:41:26.9612326Z remote: Counting objects:  49% (29/59)        
2022-12-08T15:41:26.9612604Z remote: Counting objects:  50% (30/59)        
2022-12-08T15:41:26.9612868Z remote: Counting objects:  52% (31/59)        
2022-12-08T15:41:26.9613145Z remote: Counting objects:  54% (32/59)        
2022-12-08T15:41:26.9614000Z remote: Counting objects:  55% (33/59)        
2022-12-08T15:41:26.9614282Z remote: Counting objects:  57% (34/59)        
2022-12-08T15:41:26.9614550Z remote: Counting objects:  59% (35/59)        
2022-12-08T15:41:26.9614825Z remote: Counting objects:  61% (36/59)        
2022-12-08T15:41:26.9615099Z remote: Counting objects:  62% (37/59)        
2022-12-08T15:41:26.9615373Z remote: Counting objects:  64% (38/59)        
2022-12-08T15:41:26.9615635Z remote: Counting objects:  66% (39/59)        
2022-12-08T15:41:26.9615906Z remote: Counting objects:  67% (40/59)        
2022-12-08T15:41:26.9616179Z remote: Counting objects:  69% (41/59)        
2022-12-08T15:41:26.9616455Z remote: Counting objects:  71% (42/59)        
2022-12-08T15:41:26.9616719Z remote: Counting objects:  72% (43/59)        
2022-12-08T15:41:26.9616987Z remote: Counting objects:  74% (44/59)        
2022-12-08T15:41:26.9617254Z remote: Counting objects:  76% (45/59)        
2022-12-08T15:41:26.9617519Z remote: Counting objects:  77% (46/59)        
2022-12-08T15:41:26.9617789Z remote: Counting objects:  79% (47/59)        
2022-12-08T15:41:26.9618057Z remote: Counting objects:  81% (48/59)        
2022-12-08T15:41:26.9618325Z remote: Counting objects:  83% (49/59)        
2022-12-08T15:41:26.9618581Z remote: Counting objects:  84% (50/59)        
2022-12-08T15:41:26.9618844Z remote: Counting objects:  86% (51/59)        
2022-12-08T15:41:26.9619113Z remote: Counting objects:  88% (52/59)        
2022-12-08T15:41:26.9619384Z remote: Counting objects:  89% (53/59)        
2022-12-08T15:41:26.9619645Z remote: Counting objects:  91% (54/59)        
2022-12-08T15:41:26.9619912Z remote: Counting objects:  93% (55/59)        
2022-12-08T15:41:26.9620178Z remote: Counting objects:  94% (56/59)        
2022-12-08T15:41:26.9620436Z remote: Counting objects:  96% (57/59)        
2022-12-08T15:41:26.9620707Z remote: Counting objects:  98% (58/59)        
2022-12-08T15:41:26.9620975Z remote: Counting objects: 100% (59/59)        
2022-12-08T15:41:26.9621267Z remote: Counting objects: 100% (59/59), done.        
2022-12-08T15:41:26.9621964Z remote: Compressing objects:   2% (1/46)        
2022-12-08T15:41:26.9622299Z remote: Compressing objects:   4% (2/46)        
2022-12-08T15:41:26.9622609Z remote: Compressing objects:   6% (3/46)        
2022-12-08T15:41:26.9622906Z remote: Compressing objects:   8% (4/46)        
2022-12-08T15:41:26.9623244Z remote: Compressing objects:  10% (5/46)        
2022-12-08T15:41:26.9623531Z remote: Compressing objects:  13% (6/46)        
2022-12-08T15:41:26.9623818Z remote: Compressing objects:  15% (7/46)        
2022-12-08T15:41:26.9624103Z remote: Compressing objects:  17% (8/46)        
2022-12-08T15:41:26.9624391Z remote: Compressing objects:  19% (9/46)        
2022-12-08T15:41:26.9624727Z remote: Compressing objects:  21% (10/46)        
2022-12-08T15:41:26.9625043Z remote: Compressing objects:  23% (11/46)        
2022-12-08T15:41:26.9625351Z remote: Compressing objects:  26% (12/46)        
2022-12-08T15:41:26.9625642Z remote: Compressing objects:  28% (13/46)        
2022-12-08T15:41:26.9625939Z remote: Compressing objects:  30% (14/46)        
2022-12-08T15:41:26.9626243Z remote: Compressing objects:  32% (15/46)        
2022-12-08T15:41:26.9626539Z remote: Compressing objects:  34% (16/46)        
2022-12-08T15:41:26.9626813Z remote: Compressing objects:  36% (17/46)        
2022-12-08T15:41:26.9627109Z remote: Compressing objects:  39% (18/46)        
2022-12-08T15:41:26.9627399Z remote: Compressing objects:  41% (19/46)        
2022-12-08T15:41:26.9627690Z remote: Compressing objects:  43% (20/46)        
2022-12-08T15:41:26.9627968Z remote: Compressing objects:  45% (21/46)        
2022-12-08T15:41:26.9628249Z remote: Compressing objects:  47% (22/46)        
2022-12-08T15:41:26.9628771Z remote: Compressing objects:  50% (23/46)        
2022-12-08T15:41:26.9629053Z remote: Compressing objects:  52% (24/46)        
2022-12-08T15:41:26.9629491Z remote: Compressing objects:  54% (25/46)        
2022-12-08T15:41:26.9629733Z remote: Compressing objects:  56% (26/46)        
2022-12-08T15:41:26.9629979Z remote: Compressing objects:  58% (27/46)        
2022-12-08T15:41:26.9630201Z remote: Compressing objects:  60% (28/46)        
2022-12-08T15:41:26.9630430Z remote: Compressing objects:  63% (29/46)        
2022-12-08T15:41:26.9630662Z remote: Compressing objects:  65% (30/46)        
2022-12-08T15:41:26.9630882Z remote: Compressing objects:  67% (31/46)        
2022-12-08T15:41:26.9631107Z remote: Compressing objects:  69% (32/46)        
2022-12-08T15:41:26.9631337Z remote: Compressing objects:  71% (33/46)        
2022-12-08T15:41:26.9631567Z remote: Compressing objects:  73% (34/46)        
2022-12-08T15:41:26.9638614Z remote: Compressing objects:  76% (35/46)        
2022-12-08T15:41:26.9638944Z remote: Compressing objects:  78% (36/46)        
2022-12-08T15:41:26.9639267Z remote: Compressing objects:  80% (37/46)        
2022-12-08T15:41:26.9639527Z remote: Compressing objects:  82% (38/46)        
2022-12-08T15:41:26.9639830Z remote: Compressing objects:  84% (39/46)        
2022-12-08T15:41:26.9640119Z remote: Compressing objects:  86% (40/46)        
2022-12-08T15:41:26.9640408Z remote: Compressing objects:  89% (41/46)        
2022-12-08T15:41:26.9640682Z remote: Compressing objects:  91% (42/46)        
2022-12-08T15:41:26.9640966Z remote: Compressing objects:  93% (43/46)        
2022-12-08T15:41:26.9641250Z remote: Compressing objects:  95% (44/46)        
2022-12-08T15:41:26.9641534Z remote: Compressing objects:  97% (45/46)        
2022-12-08T15:41:26.9641812Z remote: Compressing objects: 100% (46/46)        
2022-12-08T15:41:26.9642119Z remote: Compressing objects: 100% (46/46), done.        
2022-12-08T15:41:27.0525346Z remote: Total 59 (delta 28), reused 23 (delta 11), pack-reused 0        
2022-12-08T15:41:27.1884879Z From https://github.com/nlamirault/divona
2022-12-08T15:41:27.1885646Z  * [new ref]         a735d8d7fa5984e172179e20341d06d62260df6d -> pull/60/merge
2022-12-08T15:41:27.2303652Z ##[endgroup]
2022-12-08T15:41:27.2304397Z ##[group]Determining the checkout info
2022-12-08T15:41:27.2305917Z ##[endgroup]
2022-12-08T15:41:27.2306366Z ##[group]Checking out the ref
2022-12-08T15:41:27.2314628Z [command]"C:\Program Files\Git\bin\git.exe" checkout --progress --force refs/remotes/pull/60/merge
2022-12-08T15:41:27.2858639Z Note: switching to 'refs/remotes/pull/60/merge'.
2022-12-08T15:41:27.2860299Z 
2022-12-08T15:41:27.2860667Z You are in 'detached HEAD' state. You can look around, make experimental
2022-12-08T15:41:27.2861089Z changes and commit them, and you can discard any commits you make in this
2022-12-08T15:41:27.2861486Z state without impacting any branches by switching back to a branch.
2022-12-08T15:41:27.2861720Z 
2022-12-08T15:41:27.2861928Z If you want to create a new branch to retain commits you create, you may
2022-12-08T15:41:27.2862380Z do so (now or later) by using -c with the switch command. Example:
2022-12-08T15:41:27.2862631Z 
2022-12-08T15:41:27.2862843Z   git switch -c <new-branch-name>
2022-12-08T15:41:27.2863048Z 
2022-12-08T15:41:27.2863198Z Or undo this operation with:
2022-12-08T15:41:27.2863383Z 
2022-12-08T15:41:27.2863505Z   git switch -
2022-12-08T15:41:27.2863664Z 
2022-12-08T15:41:27.2863885Z Turn off this advice by setting config variable advice.detachedHead to false
2022-12-08T15:41:27.2864137Z 
2022-12-08T15:41:27.2864396Z HEAD is now at a735d8d Merge 7531414e13d10776e3fc2bf55f3ff7b2a56423d7 into 6efb7079ef8779cef842c812174252d7992aa972
2022-12-08T15:41:27.2891597Z ##[endgroup]
2022-12-08T15:41:27.3234364Z [command]"C:\Program Files\Git\bin\git.exe" log -1 --format='%H'
2022-12-08T15:41:27.3433197Z 'a735d8d7fa5984e172179e20341d06d62260df6d'
2022-12-08T15:41:27.3973539Z ##[group]Run actions/setup-python@v4.2.0
2022-12-08T15:41:27.3973883Z with:
2022-12-08T15:41:27.3974124Z   python-version: 3.10
2022-12-08T15:41:27.3974457Z   check-latest: false
2022-12-08T15:41:27.3974921Z   token: ***
2022-12-08T15:41:27.3975203Z   update-environment: true
2022-12-08T15:41:27.3975418Z ##[endgroup]
2022-12-08T15:41:27.6567595Z 
2022-12-08T15:41:27.6605692Z ##[warning]The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
2022-12-08T15:41:27.6616190Z 
2022-12-08T15:41:27.6618383Z ##[warning]The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
2022-12-08T15:41:27.6619810Z Successfully set up CPython (3.10.8)
2022-12-08T15:41:27.6865961Z ##[group]Run python -m pip install --upgrade pip
2022-12-08T15:41:27.6866494Z [36;1mpython -m pip install --upgrade pip[0m
2022-12-08T15:41:27.6866791Z [36;1mpip install ansible==7.0.0[0m
2022-12-08T15:41:27.7271300Z shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
2022-12-08T15:41:27.7271682Z env:
2022-12-08T15:41:27.7272011Z   pythonLocation: C:\hostedtoolcache\windows\Python\3.10.8\x64
2022-12-08T15:41:27.7272429Z   PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\3.10.8\x64/lib/pkgconfig
2022-12-08T15:41:27.7272885Z   Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.10.8\x64
2022-12-08T15:41:27.7273273Z   Python2_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.10.8\x64
2022-12-08T15:41:27.7273632Z   Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.10.8\x64
2022-12-08T15:41:27.7273949Z ##[endgroup]
2022-12-08T15:41:39.7301416Z Requirement already satisfied: pip in c:\hostedtoolcache\windows\python\3.10.8\x64\lib\site-packages (22.3.1)
2022-12-08T15:41:42.4792633Z Collecting ansible==7.0.0
2022-12-08T15:41:42.4899574Z   Downloading ansible-7.0.0-py3-none-any.whl (41.8 MB)
2022-12-08T15:41:43.2553081Z      --------------------------------------- 41.8/41.8 MB 21.8 MB/s eta 0:00:00
2022-12-08T15:41:43.6123826Z Collecting ansible-core~=2.14.0
2022-12-08T15:41:43.6343536Z   Downloading ansible_core-2.14.1-py3-none-any.whl (2.2 MB)
2022-12-08T15:41:43.6797828Z      ---------------------------------------- 2.2/2.2 MB 47.1 MB/s eta 0:00:00
2022-12-08T15:41:43.8959549Z Collecting cryptography
2022-12-08T15:41:43.9181060Z   Downloading cryptography-38.0.4-cp36-abi3-win_amd64.whl (2.4 MB)
2022-12-08T15:41:43.9646287Z      ---------------------------------------- 2.4/2.4 MB 51.5 MB/s eta 0:00:00
2022-12-08T15:41:44.0188620Z Collecting packaging
2022-12-08T15:41:44.9858562Z   Downloading packaging-22.0-py3-none-any.whl (42 kB)
2022-12-08T15:41:44.9859070Z      ---------------------------------------- 42.6/42.6 kB ? eta 0:00:00
2022-12-08T15:41:44.9859422Z Collecting jinja2>=3.0.0
2022-12-08T15:41:44.9859779Z   Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
2022-12-08T15:41:44.9860266Z      ---------------------------------------- 133.1/133.1 kB ? eta 0:00:00
2022-12-08T15:41:44.9860633Z Collecting resolvelib<0.9.0,>=0.5.3
2022-12-08T15:41:44.9861036Z   Downloading resolvelib-0.8.1-py2.py3-none-any.whl (16 kB)
2022-12-08T15:41:44.9861384Z Collecting PyYAML>=5.1
2022-12-08T15:41:44.9861811Z   Downloading PyYAML-6.0-cp310-cp310-win_amd64.whl (151 kB)
2022-12-08T15:41:44.9862289Z      -------------------------------------- 151.7/151.7 kB 9.4 MB/s eta 0:00:00
2022-12-08T15:41:44.9862586Z Collecting MarkupSafe>=2.0
2022-12-08T15:41:44.9863018Z   Downloading MarkupSafe-2.1.1-cp310-cp310-win_amd64.whl (17 kB)
2022-12-08T15:41:44.9863359Z Collecting cffi>=1.12
2022-12-08T15:41:44.9863725Z   Downloading cffi-1.15.1-cp310-cp310-win_amd64.whl (179 kB)
2022-12-08T15:41:44.9864206Z      ------------------------------------- 179.1/179.1 kB 11.3 MB/s eta 0:00:00
2022-12-08T15:41:44.9864537Z Collecting pycparser
2022-12-08T15:41:44.9864908Z   Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
2022-12-08T15:41:44.9865992Z      -------------------------------------- 118.7/118.7 kB 7.2 MB/s eta 0:00:00
2022-12-08T15:41:44.9866638Z Installing collected packages: resolvelib, PyYAML, pycparser, packaging, MarkupSafe, jinja2, cffi, cryptography, ansible-core, ansible
2022-12-08T15:42:38.9117866Z Successfully installed MarkupSafe-2.1.1 PyYAML-6.0 ansible-7.0.0 ansible-core-2.14.1 cffi-1.15.1 cryptography-38.0.4 jinja2-3.1.2 packaging-22.0 pycparser-2.21 resolvelib-0.8.1
2022-12-08T15:42:40.6450652Z ##[group]Run dawidd6/action-ansible-playbook@v2.6.1
2022-12-08T15:42:40.6451013Z with:
2022-12-08T15:42:40.6451265Z   playbook: ./divona_windows.yml
2022-12-08T15:42:40.6451489Z   directory: ./
2022-12-08T15:42:40.6451806Z   requirements: divona/requirements-windows.yml
2022-12-08T15:42:40.6452162Z   inventory: [all]
localhost

[all:vars]
env=windows

2022-12-08T15:42:40.6452423Z   options: -c local
--verbose

2022-12-08T15:42:40.6452686Z env:
2022-12-08T15:42:40.6452986Z   pythonLocation: C:\hostedtoolcache\windows\Python\3.10.8\x64
2022-12-08T15:42:40.6453379Z   PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\3.10.8\x64/lib/pkgconfig
2022-12-08T15:42:40.6453778Z   Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.10.8\x64
2022-12-08T15:42:40.6454153Z   Python2_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.10.8\x64
2022-12-08T15:42:40.6454522Z   Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.10.8\x64
2022-12-08T15:42:40.6454785Z ##[endgroup]
2022-12-08T15:42:40.8642194Z [command]C:\hostedtoolcache\windows\Python\3.10.8\x64\Scripts\ansible-galaxy.exe collection install -r divona/requirements-windows.yml
2022-12-08T15:42:40.9215788Z Traceback (most recent call last):
2022-12-08T15:42:40.9221978Z   File "C:\hostedtoolcache\windows\Python\3.10.8\x64\lib\runpy.py", line 196, in _run_module_as_main
2022-12-08T15:42:40.9385402Z     return _run_code(code, main_globals, None,
2022-12-08T15:42:40.9386204Z   File "C:\hostedtoolcache\windows\Python\3.10.8\x64\lib\runpy.py", line 86, in _run_code
2022-12-08T15:42:40.9386854Z     exec(code, run_globals)
2022-12-08T15:42:40.9387707Z   File "C:\hostedtoolcache\windows\Python\3.10.8\x64\Scripts\ansible-galaxy.exe\__main__.py", line 4, in <module>
2022-12-08T15:42:40.9388517Z   File "C:\hostedtoolcache\windows\Python\3.10.8\x64\lib\site-packages\ansible\cli\__init__.py", line 42, in <module>
2022-12-08T15:42:40.9389048Z     check_blocking_io()
2022-12-08T15:42:40.9389681Z   File "C:\hostedtoolcache\windows\Python\3.10.8\x64\lib\site-packages\ansible\cli\__init__.py", line 34, in check_blocking_io
2022-12-08T15:42:40.9390227Z     if not os.get_blocking(fd):
2022-12-08T15:42:40.9390735Z AttributeError: module 'os' has no attribute 'get_blocking'
2022-12-08T15:42:40.9498244Z ##[error]The process 'C:\hostedtoolcache\windows\Python\3.10.8\x64\Scripts\ansible-galaxy.exe' failed with exit code 1
2022-12-08T15:42:40.9703806Z Post job cleanup.
2022-12-08T15:42:41.0878940Z Post job cleanup.
2022-12-08T15:42:43.5967667Z [command]"C:\Program Files\Git\bin\git.exe" version
2022-12-08T15:42:43.6172218Z git version 2.38.1.windows.1
2022-12-08T15:42:43.6237652Z Temporarily overriding HOME='D:\a\_temp\6c41f155-dbaf-477a-b853-884f023d5f9e' before making global git config changes
2022-12-08T15:42:43.6238343Z Adding repository directory to the temporary git global config as a safe directory
2022-12-08T15:42:43.6248031Z [command]"C:\Program Files\Git\bin\git.exe" config --global --add safe.directory D:\a\divona\divona
2022-12-08T15:42:43.6488388Z [command]"C:\Program Files\Git\bin\git.exe" config --local --name-only --get-regexp core\.sshCommand
2022-12-08T15:42:43.6718961Z [command]"C:\Program Files\Git\bin\git.exe" submodule foreach --recursive "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2022-12-08T15:42:44.2309206Z [command]"C:\Program Files\Git\bin\git.exe" config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2022-12-08T15:42:44.2507509Z http.https://github.com/.extraheader
2022-12-08T15:42:44.2545259Z [command]"C:\Program Files\Git\bin\git.exe" config --local --unset-all http.https://github.com/.extraheader
2022-12-08T15:42:44.2784159Z [command]"C:\Program Files\Git\bin\git.exe" submodule foreach --recursive "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2022-12-08T15:42:44.7686689Z Cleaning up orphan processes
```

The Ansible playbook works fine with `macos-latest` and `ubuntu-latest`.
I don't really know how can i debug that.

Repository : https://github.com/nlamirault/divona
Job : https://github.com/nlamirault/divona/actions/runs/3649784479/jobs/6164908884

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

`windows-latest`

### Is it regression?

don't know

### Expected behavior

Correct execution of the Ansible playbook.Correct

### Actual behavior

Error during Ansible Galaxy execution using Python 3.

### Repro steps

```yaml
name: Test / Windows

on:
  # - push
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Set up Python 3
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==7.0.0

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.6.1
        with:
          playbook: ./divona_windows.yml
          directory: ./
          requirements: divona/requirements-windows.yml
          inventory: |
            [all]
            localhost

            [all:vars]
            env=windows
          options: |
            -c local
            --verbose
```

**Comment by erik-bershel** [comment]
Hello @nlamirault 
If we will take a closer look at logs we can see that error about using os.get_blocker (os interface for Python). 
https://docs.python.org/3/library/os.html#os.get_blocking
Thus, the problem is not related to any bug in our repository.
On Ansible site we can find those pages:
https://docs.ansible.com/ansible/latest/installation_guide/installation_distros.html#installing-ansible-on-windows
https://docs.ansible.com/ansible/latest/os_guide/windows_faq.html#windows-faq-ansible

**Comment by nlamirault** [comment]
OK Sorry for noise @erik-bershel
