### ISSUE TITLE
Validation build unit tests failure since agent ver 44.0.0 

### ISSUE THREAD

**Issue by wenjzha** [actions/runner-images#6873]
### Breaking changes

suffering unit tests failures related to the recent agent image ver update in 1es pool. Here is the setting for the agent under the pool:
Agent name: 'ScheduleAndExecution-Builders-CUS-Pool 1'
Agent machine name: '57050056c000000'
Current agent version: '2.213.2'
Operating System:
Microsoft Windows Server 2022
10.0.20348
Datacenter:
Runner Image
Image: windows-2022
Version: 20221120.1
Included Software: https://github.com/actions/runner-images/blob/win22/20221120.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20221120.1
1ES Hosted Pool:
SKU: Standard_D8as_v4
Image: ScheduleAndExecution-Builders-CUS-Image
Image Version: 44.0.0
Interactive Mode: False
Request Id: 2693cf00-1cd8-405e-931a-7b4dbc162e16
Pool Name: ScheduleAndExecution-Builders-CUS-Pool
Network Isolation Policy: None
Current image version: '20221120.1'
Agent running as: 'cloudtest'

Everything works fine with image version 43.0.0 (20221027.1), but start from 44.0.0, our validation build unittests start failing with package assembly issue, here I what I got for the error messages:

"System.IO.FileLoadException with message "Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.1, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

We already have the Microsoft.Extensions.Logging.Abstractions ver6.0.0.1 under the related .csproj, package.config and app.config, I even try to reinstall that again with nuget package management under vs2022, still got the same error, In addition, I try to update to higher ver such as 7.0.0.0(the latest one), got similar error:

"System.IO.FileLoadException with message "Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

Anyone can help with this?

### Target date

12/05/22

### The motivation for the changes

using the latest image to prevent any potential security issues such as s360 violation.

### Possible impact

cannot use the validation build unit tests

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Mitigation ways

I tried the older image ver (43.0.0) and it works, but using older ver might cause some potential security issues, still need to figure out what happens (anything changed/updted) with the latest one (46.0.0).

**Comment by wenjzha** [comment]
minimal repro:
Starting: Initialize job
Agent name: 'ScheduleAndExecution-Builders-CUS-Pool 1'
Agent machine name: '3b7892b2c000000'
Current agent version: '2.213.2'
Operating System
Microsoft Windows Server 2022
10.0.20348
Datacenter
Runner Image
Image: windows-2022
Version: 20221204.3
Included Software: https://github.com/actions/runner-images/blob/win22/20221204.3/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20221204.3
1ES Hosted Pool
SKU: Standard_D8as_v4
Image: ScheduleAndExecution-Builders-CUS-Image
Image Version: 46.0.0
Interactive Mode: False
Request Id: 6bf40f6e-1335-40d8-bb5e-d91f278f6933
Pool Name: ScheduleAndExecution-Builders-CUS-Pool
Network Isolation Policy: None
Current image version: '20221204.3'
Agent running as: 'cloudtest'

With the above server setting, got the following issue:
  Error Message:
   Expected a <System.ArgumentNullException> to be thrown, but found <System.IO.FileLoadException>: "
**"System.IO.FileLoadException with message "Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=6.0.0.1, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"**
     at ExecutionJobProcessorTests.ExecutionJobExecutorTests.<>c__DisplayClass0_0.<ExecutionJobExecutor_ThrowsArgumentNullException_WhenExecutionClusterOptionsIsNull>b__0()
     at FluentAssertions.Specialized.DelegateAssertions`1.InvokeSubjectWithInterception() in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Specialized\DelegateAssertions.cs:line 256
.
  Stack Trace:
     at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\LateBoundTestFramework.cs:line 21
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\TestFrameworkProvider.cs:line 41
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\DefaultAssertionStrategy.cs:line 30
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 225
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 196
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 238
   at FluentAssertions.Specialized.DelegateAssertions`1.Throw[TException](Exception exception, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Specialized\DelegateAssertions.cs:line 214
   at FluentAssertions.Specialized.DelegateAssertions`1.Throw[TException](String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Specialized\DelegateAssertions.cs:line 59
   at ExecutionJobProcessorTests.ExecutionJobExecutorTests.ExecutionJobExecutor_ThrowsArgumentNullException_WhenExecutionClusterOptionsIsNull() in D:\a\_work\1\s\src\BuildCloud\Tests\ExecutionJobProcessorTests\ExecutionJobExecutorTests.cs:line 50
  Failed ExecutionJobExecutor_CanExecuteJob_WhenSignatureIsValid [14 ms]
  Error Message:
   Test method ExecutionJobProcessorTests.ExecutionJobExecutorTests.ExecutionJobExecutor_CanExecuteJob_WhenSignatureIsValid threw exception: 
System.IO.FileLoadException: **Could not load file or assembly 'Microsoft.Extensions.Options, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)**
  Stack Trace:
      at ExecutionJobProcessorTests.ExecutionJobExecutorTests.CreateTestExecutionJobExecutor(IFixture fixture)
   at ExecutionJobProcessorTests.ExecutionJobExecutorTests.<ExecutionJobExecutor_CanExecuteJob_WhenSignatureIsValid>d__1.MoveNext() in D:\a\_work\1\s\src\BuildCloud\Tests\ExecutionJobProcessorTests\ExecutionJobExecutorTests.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)

**Comment by mikhailkoliada** [comment]
Hello @wenjzha! could you provide minimal repro steps?

**Comment by wenjzha** [comment]
I attached the minimal repro above, let me know if you need any other info

**Comment by bogdan-damian-bgd** [comment]
@wenjzha, could you provide some more clear repro steps such as the appropriate pipeline content or what we could do to reproduce the issue?

**Comment by mikhailkoliada** [comment]
Hello! Since there have no been repro steps provided I am going to close this issue. Feel free to reach us out once there is some info which could help us help you.
