### ISSUE TITLE
Android SDK/NDK Install Error on MacOS Images

### ISSUE THREAD

**Issue by SahilAshar** [actions/runner-images#7015]
### Description

Starting around Jan 23rd, 2023, our MacOS 12 images are failing to install the Android NDK with this error:
```
2023-01-30T17:56:32.9363400Z + /Users/runner/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager --install 'ndk;22.1.7171670'
2023-01-30T17:56:33.1477830Z Error: A JNI error has occurred, please check your installation and try again
2023-01-30T17:56:33.1484110Z Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/prefs/AndroidLocationsProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
2023-01-30T17:56:33.1492600Z 	at java.lang.ClassLoader.defineClass1(Native Method)
2023-01-30T17:56:33.1493190Z 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
2023-01-30T17:56:33.1493800Z 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2023-01-30T17:56:33.1494360Z 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
2023-01-30T17:56:33.1494890Z 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
2023-01-30T17:56:33.1495430Z 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
2023-01-30T17:56:33.1495930Z 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
2023-01-30T17:56:33.1496420Z 	at java.security.AccessController.doPrivileged(Native Method)
2023-01-30T17:56:33.1496920Z 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
2023-01-30T17:56:33.1497430Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
2023-01-30T17:56:33.1497950Z 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
2023-01-30T17:56:33.1498460Z 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
2023-01-30T17:56:33.1498940Z 	at java.lang.Class.getDeclaredMethods0(Native Method)
2023-01-30T17:56:33.1499430Z 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
2023-01-30T17:56:33.1499960Z 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
2023-01-30T17:56:33.1502380Z 	at java.lang.Class.getMethod0(Class.java:3018)
2023-01-30T17:56:33.1502870Z 	at java.lang.Class.getMethod(Class.java:1784)
2023-01-30T17:56:33.1503430Z 	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
2023-01-30T17:56:33.1504010Z 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
```

This looks like duplicates of #6960 and #6985. It also looks like this issue was possibly fixed in PR #6965, but I don't see if/where this fix was merged into a recent release. Would appreciate any guidance with this 😊

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

As of recently, the failure is occurring with:
```
Runner Image
Image: macos-12
Version: 20230117.3
Included Software: https://github.com/actions/runner-images/blob/macOS-12/20230117.3/images/macos/macos-12-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230117.3
```

Around Jan 24th, the failure was occurring with this image (which seems to no longer exist):
```
Runner Image
Image: macos-12
Version: 20230120.1
Included Software: https://github.com/actions/runner-images/blob/macOS-12/20230120.1/images/macos/macos-12-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230120.1
```

### Is it regression?

It looks like the last pass of our pipeline was on Jan 20th, 2023, but also with MacOS-12 Version 20230117.3. 

### Expected behavior

Expected output is that the NDK installs properly. 
 
[ExpectedOutputForAndroidNDKInstall.txt](https://github.com/actions/runner-images/files/10538896/ExpectedOutputForAndroidNDKInstall.txt)

### Actual behavior

The current output is that the NDK install fails with the error I mentioned above.

[FailureOutputForAndroidNDKInstall.txt](https://github.com/actions/runner-images/files/10538897/FailureOutputForAndroidNDKInstall.txt)

### Repro steps

Repro Steps:

1. Spin up a new `macos-latest` image. This should currently point at `macos-12 v20230117.3`.
2. Attempt to install Android NDK [r22b](https://github.com/android/ndk/wiki/Unsupported-Downloads#r22b), `22.1.7171670`.
3. NDK install will fail with the above error.

**Comment by mikhailkoliada** [comment]
@SahilAshar please sync your main, these fixes are merged :)

**Comment by SahilAshar** [comment]
Thanks for the updates y'all!

@mikhailkoliada as I mentioned in the issue, we're using this through one of the [Microsoft-hosted agents](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml) on ADO, so no way for us to update it on our own unfortunately. But based on what @bogdan-damian-bgd is saying, we should expect a new release of the MacOS image this week? 

We've been unable to validate our Android releases in our pipelines for the last week or so due to the broken image, so any help getting out a fix out would be greatly appreciated :)

**Comment by SahilAshar** [comment]
Hi @mikhailkoliada & @bogdan-damian-bgd -

Our ADO pipelines have updated to the newest MacOS-12 image y'all released.

```
Image: macos-12
Version: 20230205.1
Included Software: https://github.com/actions/runner-images/blob/macOS-12/20230205.1/images/macos/macos-12-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230205.1
```

Unfortunately, it looks like this failure is still occurring, with the exact same logs I've attached above. Any assistance with this would be appreciated.
