### ISSUE TITLE
Nodetool task does not always work as intended

### ISSUE THREAD

**Issue by GurliGebis** [actions/runner-images#7168]
### Description

After the latest upgrade to NodeJS 18 being the default, we have started seeing an issue.

We use the NodeTool task to install NodeJS 14.x, which has been working just fine up until now.
For the past few days, we have seen that it, only sometimes, installs the 14.x version, but then, right after that, it keeps using the 18.x version, which makes it fail.
Once it fails, we normally just clock rerun failed jobs, and then it works fine.
So it is not every time it fails - my guess is that not all the hosted agents has been upgraded to the latest image, so it might be lucky that the rerun uses an agent with the old image.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Windows 2019 20230214.1

### Is it regression?

Windows 2019 20230129.2

### Expected behavior

Once the NodeTool task has been run, it should always that version going forward.

### Actual behavior

Randomly, it keeps using the Nodejs 18.x version, even when another version has been installed with the NodeTool task. 

### Repro steps

1: Create a pipeline with the NodeTool task and have it install the version 14.x
2: Run a command to check which nodejs version is being used.
3: Run the pipeline multiple times (might talk several rund for it to trigger) - eventually, it will use the 18.x version instead of the installed version.

**Comment by GurliGebis** [comment]
Output of the NodeTool task:

> 2023-02-21T13:37:00.3616065Z ##[section]Starting: Install NPM version 14.18.x
2023-02-21T13:37:00.3772002Z ==============================================================================
2023-02-21T13:37:00.3772251Z Task         : Node.js tool installer
2023-02-21T13:37:00.3772395Z Description  : Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH
2023-02-21T13:37:00.3772659Z Version      : 0.213.0
2023-02-21T13:37:00.3772784Z Author       : Microsoft Corporation
2023-02-21T13:37:00.3772932Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/node-js
2023-02-21T13:37:00.3773132Z ==============================================================================
2023-02-21T13:37:01.4324253Z Downloading: https://nodejs.org/dist/v14.18.3/node-v14.18.3-win-x64.7z
2023-02-21T13:39:37.6345298Z ##[section]Finishing: Install NPM version 14.18.x

Output of the npm command run afterwards:

> 2023-02-21T13:41:07.4746696Z ##[section]Starting: Build frontend
2023-02-21T13:41:07.4867499Z ==============================================================================
2023-02-21T13:41:07.4867756Z Task         : npm
2023-02-21T13:41:07.4867871Z Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts.
2023-02-21T13:41:07.4868176Z Version      : 1.215.1
2023-02-21T13:41:07.4868316Z Author       : Microsoft Corporation
2023-02-21T13:41:07.4868461Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/npm
2023-02-21T13:41:07.4868659Z ==============================================================================
2023-02-21T13:41:08.7216157Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" --version"
2023-02-21T13:41:11.4428953Z 9.3.1
2023-02-21T13:41:14.2623651Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" config list"
2023-02-21T13:41:15.5557817Z ; "builtin" config from C:\Program Files\nodejs\node_modules\npm\npmrc
2023-02-21T13:41:15.5559034Z 
2023-02-21T13:41:15.5559426Z ; prefix = "C:\\Users\\VssAdministrator\\AppData\\Roaming\\npm" ; overridden by env
2023-02-21T13:41:15.5559641Z 
2023-02-21T13:41:15.5559977Z ; "global" config from C:\npm\prefix\etc\npmrc
2023-02-21T13:41:15.5560206Z 
2023-02-21T13:41:15.5560603Z cache = "C:\\npm\\cache" 
2023-02-21T13:41:15.5560794Z 
2023-02-21T13:41:15.5561723Z ; "env" config from environment
2023-02-21T13:41:15.5562012Z 
2023-02-21T13:41:15.5562459Z prefix = "C:\\npm\\prefix" 
2023-02-21T13:41:15.5562970Z userconfig = "D:\\a\\1\\npm\\14591.npmrc" 
2023-02-21T13:41:15.5563251Z 
2023-02-21T13:41:15.5563764Z ; node bin location = C:\Program Files\nodejs\node.exe
2023-02-21T13:41:15.5564347Z ; node version = v18.14.0
2023-02-21T13:41:15.5564900Z ; npm local prefix = D:\a\1\s\frontline
2023-02-21T13:41:15.5565442Z ; npm version = 9.3.1
2023-02-21T13:41:15.5565969Z ; cwd = D:\a\1\s\frontline
2023-02-21T13:41:15.5566541Z ; HOME = C:\Users\VssAdministrator
2023-02-21T13:41:15.5567169Z ; Run `npm config ls -l` to show all defaults.
2023-02-21T13:41:15.5571306Z [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" run build"
2023-02-21T13:41:22.5865298Z 
2023-02-21T13:41:22.5866341Z node:internal/crypto/hash:71
2023-02-21T13:41:22.5866817Z > build
2023-02-21T13:41:22.5867361Z > npm run clean && cross-env NODE_ENV=production webpack --mode production
2023-02-21T13:41:22.5867674Z 
2023-02-21T13:41:22.5867802Z 
2023-02-21T13:41:22.5868160Z > clean
2023-02-21T13:41:22.5868840Z > rimraf dist && rimraf ../docker/deploy/pro-rendering/wwwroot/frontend && rimraf ../docker/deploy/med-rendering/wwwroot/frontend
2023-02-21T13:41:22.5869276Z 
2023-02-21T13:41:22.5869766Z   this[kHandle] = new _Hash(algorithm, xofLen);
2023-02-21T13:41:22.5870226Z                   ^
2023-02-21T13:41:22.5870376Z 
2023-02-21T13:41:22.5870872Z Error: error:0308010C:digital envelope routines::unsupported
2023-02-21T13:41:22.5871411Z     at new Hash (node:internal/crypto/hash:71:19)
2023-02-21T13:41:22.5871803Z     at Object.createHash (node:crypto:133:10)
2023-02-21T13:41:22.5872286Z     at module.exports (D:\a\1\s\frontline\node_modules\webpack\lib\util\createHash.js:135:53)
2023-02-21T13:41:22.5872863Z     at NormalModule._initBuildHash (D:\a\1\s\frontline\node_modules\webpack\lib\NormalModule.js:417:16)
2023-02-21T13:41:22.5873659Z     at D:\a\1\s\frontline\node_modules\webpack\lib\NormalModule.js:452:10
2023-02-21T13:41:22.5874466Z     at D:\a\1\s\frontline\node_modules\webpack\lib\NormalModule.js:323:13
2023-02-21T13:41:22.5875301Z     at D:\a\1\s\frontline\node_modules\loader-runner\lib\LoaderRunner.js:367:11
2023-02-21T13:41:22.5876128Z     at D:\a\1\s\frontline\node_modules\loader-runner\lib\LoaderRunner.js:233:18
2023-02-21T13:41:22.5877017Z     at context.callback (D:\a\1\s\frontline\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
2023-02-21T13:41:22.5877938Z     at D:\a\1\s\frontline\node_modules\@akqa-frontline\js-config-webpack-plugin\node_modules\babel-loader\lib\index.js:55:103 {
2023-02-21T13:41:22.5880847Z   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
2023-02-21T13:41:22.5881596Z   library: 'digital envelope routines',
2023-02-21T13:41:22.5882102Z   reason: 'unsupported',
2023-02-21T13:41:22.5882576Z   code: 'ERR_OSSL_EVP_UNSUPPORTED'
2023-02-21T13:41:22.5882998Z }
2023-02-21T13:41:22.5883089Z 
2023-02-21T13:41:22.5883327Z Node.js v18.14.0
2023-02-21T13:41:22.6390972Z ##[warning]Couldn't find a debug log in the cache or working directory
2023-02-21T13:41:22.6408061Z ##[error]Error: Npm failed with return code: 1
2023-02-21T13:41:22.6429495Z ##[section]Finishing: Build frontend

**Comment by GurliGebis** [comment]
As you can see, it uses the 18.x, even though 14.x has just been installed

**Comment by mikhailkoliada** [comment]
Hello! This repository contains the image specs for hosted runners, please report AzDo tasks issues to https://github.com/microsoft/azure-pipelines-tasks

**Comment by GurliGebis** [comment]
@mikhailkoliada also when this clearly is an issue with the latest image from in here?
