### ISSUE TITLE
Az Bicep fails to install

### ISSUE THREAD

**Issue by milkyware** [actions/runner-images#7292]
### Description

When installing the Az Bicep cli in an Azure Pipeline using `az bicep install`, the pipeline fails with the below error

``` bash
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: No section: 'bicep'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 3648, in install_bicep_cli
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 141, in ensure_bicep_installation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 99, in get
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 94, in get
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 208, in get
  File "configparser.py", line 783, in get
  File "configparser.py", line 1154, in _unify_values
configparser.NoSectionError: No section: 'bicep'
```

This seems to work in windows image version 20230226.1 (potentially others up until 20230307.2 but don't have pipeline history). The same for ubuntu 22.04 where mast last record of this command working is 20230305.1 and now broken in 20230313.1.

Let me know if any more detail is required

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Private build

Runner Image
Image: windows-2022
Version: 20230307.2
Included Software: https://github.com/actions/runner-images/blob/win22/20230307.2/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230307.2

Image: ubuntu-22.04
Version: 20230313.1
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230313.1/images/linux/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230313.1

### Is it regression?

yes

### Expected behavior

Bicep Cli installs successfully

### Actual behavior

Error in description is thrown

### Repro steps

1. Create Azure pipeline
2. Set vm image pool to **windows-latest** or **ubuntu-latest**
3. Add step to install Bicep Cli
4. Run pipeline
5. Check image version is 20230307.2 or 20230313.1

**Comment by erik-bershel** [comment]
Hello @milkyware!
It's bug in Azure CLI 2.46. Details here: https://github.com/Azure/azure-cli/issues/25710. We cannot revert Azure CLI, but you may use that workaround to avoid that nasty error: https://github.com/Azure/azure-cli/issues/25710#issuecomment-1469479711

**Comment by milkyware** [comment]
Hi @erik-bershel. Thanks for that. Shall keep an eye on the az CLI issue

**Comment by erik-bershel** [comment]
@milkyware I'm almost sure they will cover it with next release as always. :) But it will take some time.

**Comment by m-soltani** [comment]
would be perfect if a fix is being released soon.:)
