### ISSUE TITLE
GenerateResourceandImage failing on Function Get-PackerTemplatePath 

### ISSUE THREAD

**Issue by greadtm** [actions/runner-images#8849]
### Description

I attempting to create a new scaleset with ImageType=Ubuntu2204.
I obtained the latest code from the GIT repo based on branch=main.
https://github.com/actions/runner-images.git

I am executing the script 

GenerateResourcesAndImage -SubscriptionId SubID  -ResourceGroupName groupname -ImageGenerationRepositoryRoot "$pwd" -ImageType Ubuntu2204 -AzureLocation "centralus" -AzureTenantId TenantID -AzureClientID clientID -AzureClientSecret secret

The script above knows that Ubuntu2204 is type=4 and attempts to pull the template value ubuntu-22.04.pkr.hcl.

The script fails on the function call Get-PackerTemplatePath.
Get-PackerTemplatePath : A positional parameter cannot be found that accepts argument 'ubuntu-22.04.pkr.hcl'.

1) I am not sure why its including the . at the end of the call.
2) I tried renaming the hcl file in the template dir and its not even getting that far.

Any ideas on how I can get passed this issue? This was working as of a few weeks ago.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

This is latest git clone from main branch.

### Is it regression?

yes

### Expected behavior

GenerateResourceandImage script executes without the function failure.

### Actual behavior

See above.

### Repro steps

See steps in description.

**Comment by vpolikarpov-akvelon** [comment]
Hey @greadtm. We don't observe such behavior so wouldn't you mind providing a bit more information? What environment do you run script in? What's your OS and PowerShell version? Also, could you please share a complete log so we can examine it?

**Comment by greadtm** [comment]
Windows Server 2016
PSVersion                      5.1.14393.5582

2023-11-17T16:15:04.1754409Z Cloning into 'd:\vmscalesetlinop22dr'...
2023-11-17T16:15:05.4946960Z Cloning into 'd:\VMImage\virtenvlinop22dr'...
2023-11-17T16:15:07.3749161Z VERBOSE: Loading module from path 'D:\VMImage\virtenvlinop22dr\helpers\GenerateResourcesAndImage.ps1'.
2023-11-17T16:15:07.3846325Z VERBOSE: Dot-sourcing the script file 'D:\VMImage\virtenvlinop22dr\helpers\GenerateResourcesAndImage.ps1'.
2023-11-17T16:15:07.4678189Z Latest commit: Date: Fri Nov 17 16:31:49 2023 +0100; Commit: 50ae10289a1d019551858f6a174f78d2e212bed4 - [Ubuntu] Pin sha256 for docker-compose and Alibaba Cloud CLI (#8790); Author: sergei-pyshnoi <121864472+sergei-pyshnoi@users.noreply.github.com>.
2023-11-17T16:15:07.4868901Z ##[debug]Error record:
2023-11-17T16:15:07.5806488Z ##[debug]Get-PackerTemplatePath : A positional parameter cannot be found that accepts argument 'ubuntu-22.04.pkr.hcl'.
2023-11-17T16:15:07.5819648Z ##[debug]At D:\VMImage\virtenvlinop22dr\helpers\GenerateResourcesAndImage.ps1:161 char:21
2023-11-17T16:15:07.5830733Z ##[debug]+ ... platePath = Get-PackerTemplatePath -RepositoryRoot $ImageGenerationRe ...
2023-11-17T16:15:07.5841565Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-11-17T16:15:07.5852580Z ##[debug]    + CategoryInfo          : InvalidArgument: (:) [Get-PackerTemplatePath], ParameterBindingException
2023-11-17T16:15:07.5862969Z ##[debug]    + FullyQualifiedErrorId : PositionalParameterNotFound,Get-PackerTemplatePath
2023-11-17T16:15:07.5873523Z ##[debug] 
2023-11-17T16:15:07.5890722Z ##[debug]Script stack trace:
2023-11-17T16:15:07.5919080Z ##[debug]at Get-PackerTemplatePath, D:\VMImage\virtenvlinop22dr\helpers\GenerateResourcesAndImage.ps1: line 30
2023-11-17T16:15:07.5930727Z ##[debug]at GenerateResourcesAndImage, D:\VMImage\virtenvlinop22dr\helpers\GenerateResourcesAndImage.ps1: line 161
2023-11-17T16:15:07.5942831Z ##[debug]at <ScriptBlock>, D:\SharedRel1\_temp\0156d08e-3f2a-455e-8d26-b09834dc869a.ps1: line 63
2023-11-17T16:15:07.5953461Z ##[debug]at <ScriptBlock>, <No file>: line 1
2023-11-17T16:15:07.5970393Z ##[debug]Exception:
2023-11-17T16:15:07.6004129Z ##[debug]System.Management.Automation.ParameterBindingException: A positional parameter cannot be found that accepts argument 'ubuntu-22.04.pkr.hcl'.
2023-11-17T16:15:07.6014642Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2023-11-17T16:15:07.6024998Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2023-11-17T16:15:07.6140933Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2023-11-17T16:15:07.6152440Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2023-11-17T16:15:07.6165618Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2023-11-17T16:15:07.6177334Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2023-11-17T16:15:07.6188012Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2023-11-17T16:15:07.6198463Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2023-11-17T16:15:07.6209138Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2023-11-17T16:15:07.6386114Z ##[error]A positional parameter cannot be found that accepts argument 'ubuntu-22.04.pkr.hcl'.
2023-11-17T16:15:07.6395942Z ##[debug]Processed: ##vso[task.logissue type=error]A positional parameter cannot be found that accepts argument 'ubuntu-22.04.pkr.hcl'.
2023-11-17T16:15:07.6844724Z ##[debug]Exit code: 1
2023-11-17T16:15:07.6880963Z ##[debug]Leaving Invoke-VstsTool.
2023-11-17T16:15:07.7062380Z ##[error]PowerShell exited with code '1'.
2023-11-17T16:15:07.7063369Z ##[debug]Processed: ##vso[task.logissue type=error]PowerShell exited with code '1'.
2023-11-17T16:15:07.7118604Z ##[debug]Processed: ##vso[task.complete result=Failed]Error detected
2023-11-17T16:15:07.7134972Z ##[debug]Loading module from path 'D:\SharedRel1\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.231.0\ps_modules\VstsAzureHelpers_\VstsAzureHelpers_.psm1'.
2023-11-17T16:15:07.7221314Z ##[debug]$OVERRIDING $global:DebugPreference from 'Continue' to 'SilentlyContinue'.
2023-11-17T16:15:07.7242726Z ##[debug]Loading resource strings from: D:\SharedRel1\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.231.0\ps_modules\VstsAzureHelpers_/module.json
2023-11-17T16:15:07.7459285Z ##[debug]Loaded 15 strings.
2023-11-17T16:15:07.7487782Z ##[debug]SYSTEM_CULTURE: 'en-US'
2023-11-17T16:15:07.7509051Z ##[debug]Loading resource strings from: D:\SharedRel1\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.231.0\ps_modules\VstsAzureHelpers_\Strings\resources.resjson\en-US\resources.resjson
2023-11-17T16:15:07.7724748Z ##[debug]Loaded 15 strings.
2023-11-17T16:15:07.7763462Z ##[debug]Entering Get-VstsWebProxy.
2023-11-17T16:15:07.7860893Z ##[debug]AGENT_VERSION: '2.213.2'
2023-11-17T16:15:07.7928592Z ##[debug]AGENT_PROXYURL (empty)
2023-11-17T16:15:07.7972719Z ##[debug]AGENT_PROXYUSERNAME (empty)
2023-11-17T16:15:07.8014369Z ##[debug]AGENT_PROXYPASSWORD (empty)
2023-11-17T16:15:07.8055077Z ##[debug]AGENT_PROXYBYPASSLIST (empty)
2023-11-17T16:15:07.8096411Z ##[debug]Leaving Get-VstsWebProxy.
2023-11-17T16:15:07.8285148Z ##[debug]Loading module from path 'D:\SharedRel1\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.231.0\ps_modules\TlsHelper_\TlsHelper_.psm1'.
2023-11-17T16:15:07.8385255Z ##[debug]Loading resource strings from: D:\SharedRel1\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.231.0\ps_modules\TlsHelper_/module.json
2023-11-17T16:15:07.8456857Z ##[debug]Loaded 3 strings.
2023-11-17T16:15:07.8484222Z ##[debug]SYSTEM_CULTURE: 'en-US'
2023-11-17T16:15:07.8506506Z ##[debug]Loading resource strings from: D:\SharedRel1\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\5.231.0\ps_modules\TlsHelper_\Strings\resources.resjson\en-US\resources.resjson

**Comment by greadtm** [comment]
It looks like the GenerateIResourcesAndImage PS maybe looking for templates under:
images\linux\templates and not under new structure of images\ubuntu\templates.

**Comment by wojsmol** [comment]
@greadtm As we can see here https://github.com/actions/runner-images/blob/50625a842ad09f741de40651332bdc6064c7f0a9/helpers/GenerateResourcesAndImage.ps1#L19-L36 newest `GenerateIResourcesAndImage` is updated for this changes - pull latest `main` and try again.

**Comment by greadtm** [comment]
I just cloned from main and the same error.

2023-11-20T20:53:54.0825692Z Cloning into 'd:\VMImage\virtenvlinop22dr'...
2023-11-20T20:53:55.7678656Z VERBOSE: Loading module from path 'D:\VMImage\virtenvlinop22dr\helpers\GenerateResourcesAndImage.ps1'.
2023-11-20T20:53:55.7777293Z VERBOSE: Dot-sourcing the script file 'D:\VMImage\virtenvlinop22dr\helpers\GenerateResourcesAndImage.ps1'.
2023-11-20T20:53:55.8516132Z Latest commit: Date: Mon Nov 20 18:18:40 2023 +0100; Commit: 50625a842ad09f741de40651332bdc6064c7f0a9 - Fix SBOM workflow logic (#8848); Author: Erik Bershel <110455084+erik-bershel@users.noreply.github.com>.
2023-11-20T20:53:55.8701269Z ##[debug]Error record:
2023-11-20T20:53:55.9679435Z ##[debug]Get-PackerTemplatePath : A positional parameter cannot be found that accepts argument 'ubuntu-22.04.pkr.hcl'.
2023-11-20T20:53:55.9691404Z ##[debug]At D:\VMImage\virtenvlinop22dr\helpers\GenerateResourcesAndImage.ps1:161 char:21
2023-11-20T20:53:55.9704058Z ##[debug]+ ... platePath = Get-PackerTemplatePath -RepositoryRoot $ImageGenerationRe ...
2023-11-20T20:53:55.9718413Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-11-20T20:53:55.9730542Z ##[debug]    + CategoryInfo          : InvalidArgument: (:) [Get-PackerTemplatePath], ParameterBindingException
2023-11-20T20:53:55.9742276Z ##[debug]    + FullyQualifiedErrorId : PositionalParameterNotFound,Get-PackerTemplatePath
2023-11-20T20:53:55.9754153Z ##[debug] 
2023-11-20T20:53:55.9776162Z ##[debug]Script stack trace:
2023-11-20T20:53:55.9809656Z ##[debug]at Get-PackerTemplatePath, D:\VMImage\virtenvlinop22dr\helpers\GenerateResourcesAndImage.ps1: line 30
2023-11-20T20:53:55.9821819Z ##[debug]at GenerateResourcesAndImage, D:\VMImage\virtenvlinop22dr\helpers\GenerateResourcesAndImage.ps1: line 161
2023-11-20T20:53:55.9833516Z ##[debug]at <ScriptBlock>, D:\SharedRel1\_temp\21dace6d-a95b-4c02-a000-8800e1ee3499.ps1: line 63
2023-11-20T20:53:55.9849407Z ##[debug]at <ScriptBlock>, <No file>: line 1
2023-11-20T20:53:55.9871012Z ##[debug]Exception:
2023-11-20T20:53:56.0024544Z ##[debug]System.Management.Automation.ParameterBindingException: A positional parameter cannot be found that accepts argument 'ubuntu-22.04.pkr.hcl'.
2023-11-20T20:53:56.0036982Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2023-11-20T20:53:56.0050193Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2023-11-20T20:53:56.0064702Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2023-11-20T20:53:56.0079544Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2023-11-20T20:53:56.0091329Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2023-11-20T20:53:56.0102613Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2023-11-20T20:53:56.0113705Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2023-11-20T20:53:56.0125508Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2023-11-20T20:53:56.0136326Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2023-11-20T20:53:56.0311961Z ##[error]A positional parameter cannot be found that accepts argument 'ubuntu-22.04.pkr.hcl'.
2023-11-20T20:53:56.0320059Z ##[debug]Processed: ##vso[task.logissue type=error]A positional parameter cannot be found that accepts argument 'ubuntu-22.04.pkr.hcl'.
2023-11-20T20:53:56.0799124Z ##[debug]Exit code: 1
2023-11-20T20:53:56.0843124Z ##[debug]Leaving Invoke-VstsTool.
2023-11-20T20:53:56.1038620Z ##[error]PowerShell exited with code '1'.
2023-11-20T20:53:56.1039272Z ##[debug]Processed: ##vso[task.logissue type=error]PowerShell exited with code '1'.
2023-11-20T20:53:56.1097777Z ##[debug]Processed: ##vso[task.complete result=Failed]Error detected

**Comment by greadtm** [comment]
Hi @vpolikarpov-akvelon. Your fix works. I am able to execute the script with PS 5.1.
Thanks
Greg
