### ISSUE TITLE
Chocolatey error in Windows builds

### ISSUE THREAD

**Issue by manongjohn** [actions/runner-images#9476]
### Description

Chocolatey fails for `Invalid credentials specified.` in Windows builds

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.314.1'

### Is it regression?

No

### Expected behavior

Chocolatey package installs successfully

### Actual behavior

```
Chocolatey v2.2.2
Installing the following packages:
opencv
By installing, you accept licenses for the packages.
Invalid credentials specified.
Please provide credentials for: https://community.chocolatey.org/api/v2/
User name: Password: Chocolatey had an error on fv-az[13](https://github.com/tahoma2d/tahoma2d/actions/runs/8218723884/job/22475956302#step:3:14)87-742 (with user runneradmin):
System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at chocolatey.infrastructure.commandline.ReadKeyTimeout.ConsoleReadKey()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at chocolatey.infrastructure.commandline.ReadKeyTimeout.ConsoleReadKey()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

### Repro steps

Install a Chocolatey package in a Windows runner

**Comment by mikhailkoliada** [comment]
It is an error on choco api side, not something we can fix, please report to choco maintainer directly

**Comment by steviecoaster** [comment]
> It is an error on choco api side, not something we can fix, please report to choco maintainer directly

No this isn't our side. This is a source configuration issue. Something is corrupted.

**Comment by steviecoaster** [comment]
Actually. It looks like something is wrong with Cloudflare. So it's not us, and it's not this. Our Ops team is looking at it.

**Comment by manongjohn** [comment]
Looks like the issue was fixed.  I was able to restart my failed build and the Chocolatey packages successfully downloaded and installed.
