### ISSUE TITLE
Github Action checkout v3 fails on fetching - git error - The process '/usr/bin/git' failed with exit code 128

### ISSUE THREAD

**Issue by yardensade** [actions/runner-images#9632]
### Description

Many actions are all of a sudden failing today on checkout, absolutely nothing changed on my side.

This is the action step which I had for months:
```
runs:
  using: "composite"
  steps:
    - name: Check out ****-github-actions
      uses: actions/checkout@v3
      with:
        repository: ****-github-action
        ref: main
        path: ./.github/actions/****
```

Attaching logs:
```
2024-04-04T07:33:22.8383374Z ##[group]Run actions/checkout@v3
2024-04-04T07:33:22.8383775Z with:
2024-04-04T07:33:22.8384133Z   repository: ****
2024-04-04T07:33:22.8384632Z   ref: main
2024-04-04T07:33:22.8384970Z   path: ./.github/actions/****
2024-04-04T07:33:22.8385641Z   token: ****
2024-04-04T07:33:22.8385991Z   ssh-strict: true
2024-04-04T07:33:22.8386320Z   persist-credentials: true
2024-04-04T07:33:22.8386662Z   clean: true
2024-04-04T07:33:22.8386998Z   sparse-checkout-cone-mode: true
2024-04-04T07:33:22.8387342Z   fetch-depth: 1
2024-04-04T07:33:22.8387633Z   fetch-tags: false
2024-04-04T07:33:22.8388019Z   lfs: false
2024-04-04T07:33:22.8388302Z   submodules: false
2024-04-04T07:33:22.8388649Z   set-safe-directory: true
2024-04-04T07:33:22.8388989Z ##[endgroup]
2024-04-04T07:33:23.0326554Z Syncing repository: ****
2024-04-04T07:33:23.0328818Z ##[group]Getting Git version info
2024-04-04T07:33:23.0330105Z Working directory is '/home/runner/work/****'
2024-04-04T07:33:23.0331231Z [command]/usr/bin/git version
2024-04-04T07:33:23.0367581Z git version 2.43.2
2024-04-04T07:33:23.0392396Z ##[endgroup]
2024-04-04T07:33:23.0414859Z Temporarily overriding HOME='/home/runner/work/_temp/d405e998-3c6c-4296-9916-fbb53712203f' before making global git config changes
2024-04-04T07:33:23.0417435Z Adding repository directory to the temporary git global config as a safe directory
2024-04-04T07:33:23.0420012Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work****
2024-04-04T07:33:23.0457392Z ##[group]Initializing the repository
2024-04-04T07:33:23.0479936Z [command]/usr/bin/git init /home/runner/work/****
2024-04-04T07:33:23.0542829Z hint: Using 'master' as the name for the initial branch. This default branch name
2024-04-04T07:33:23.0545017Z hint: is subject to change. To configure the initial branch name to use in all
2024-04-04T07:33:23.0546604Z hint: of your new repositories, which will suppress this warning, call:
2024-04-04T07:33:23.0547984Z hint: 
2024-04-04T07:33:23.0549297Z hint: 	git config --global init.defaultBranch <name>
2024-04-04T07:33:23.0550537Z hint: 
2024-04-04T07:33:23.0552992Z hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
2024-04-04T07:33:23.0555023Z hint: 'development'. The just-created branch can be renamed via this command:
2024-04-04T07:33:23.0556710Z hint: 
2024-04-04T07:33:23.0557845Z hint: 	git branch -m <name>
2024-04-04T07:33:23.0559837Z Initialized empty Git repository in /home/runner/work/****
2024-04-04T07:33:23.0564373Z [command]/usr/bin/git remote add origin https://github.com/****
2024-04-04T07:33:23.0599952Z ##[endgroup]
2024-04-04T07:33:23.0601276Z ##[group]Disabling automatic garbage collection
2024-04-04T07:33:23.0603564Z [command]/usr/bin/git config --local gc.auto 0
2024-04-04T07:33:23.0632098Z ##[endgroup]
2024-04-04T07:33:23.0633569Z ##[group]Setting up auth
2024-04-04T07:33:23.0639491Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-04-04T07:33:23.0667251Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-04-04T07:33:23.0965730Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-04-04T07:33:23.0978576Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-04-04T07:33:23.1155656Z [command]/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
2024-04-04T07:33:23.1195621Z ##[endgroup]
2024-04-04T07:33:23.1197545Z ##[group]Fetching the repository
2024-04-04T07:33:23.1206635Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/main*:refs/remotes/origin/main* +refs/tags/main*:refs/tags/main*
2024-04-04T07:33:23.1258870Z /usr/lib/git-core/git-remote-https: error while loading shared libraries: /lib/x86_64-linux-gnu/libgssapi_krb5.so.2: invalid ELF header
2024-04-04T07:33:23.1266961Z The process '/usr/bin/git' failed with exit code 128
2024-04-04T07:33:23.1268196Z Waiting 16 seconds before trying again
2024-04-04T07:33:39.1303048Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/main*:refs/remotes/origin/main* +refs/tags/main*:refs/tags/main*
2024-04-04T07:33:39.1341658Z /usr/lib/git-core/git-remote-https: error while loading shared libraries: /lib/x86_64-linux-gnu/libgssapi_krb5.so.2: invalid ELF header
2024-04-04T07:33:39.1352537Z The process '/usr/bin/git' failed with exit code 128
2024-04-04T07:33:39.1353281Z Waiting 19 seconds before trying again
2024-04-04T07:33:58.1456060Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/main*:refs/remotes/origin/main* +refs/tags/main*:refs/tags/main*
2024-04-04T07:33:58.1494241Z /usr/lib/git-core/git-remote-https: error while loading shared libraries: /lib/x86_64-linux-gnu/libgssapi_krb5.so.2: invalid ELF header
2024-04-04T07:33:58.1571200Z ##[error]The process '/usr/bin/git' failed with exit code 128
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu-20.04 20240403.1.0

### Is it regression?

yes

### Expected behavior

git should not fail on checkout

### Actual behavior

git fails on checkout

### Repro steps

simply use checkout v3 with ubuntu 20:04 runner and it will fail, sporadically

**Comment by shamil-mubarakshin** [comment]
Hello @yardensade, I couldn't reproduce the issue, [first job](https://github.com/shamil-mubarakshin/tests-repository/actions/runs/8553179115/job/23436251338#step:1:9), [second job](https://github.com/shamil-mubarakshin/tests-repository/actions/runs/8553179115/job/23436378434#step:1:9). I would suggest contacting https://github.com/actions/checkout for further troubleshooting

**Comment by yardensade** [comment]
As I said this happens sporadically, the fact you ran it twice does not mean there is no issue.
I am running thousands of actions like that a day, and it happened to me dozens of times today, while most of the time it works.

I would not have taken my time to contact you if it was not very important, unlike the ubuntu version change that started this, checkout was not changed recently.

I am not the only one to experience this, I know for a fact it happens to others as well.

**Comment by chris-griffin** [comment]
We are also seeing this as new behavior. It is also sporadic, and happening about 1/100 runs. The first time I observed it was around the incident GitHub had last night so perhaps that incident is really ongoing?

```

Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +18e82eac24081b13bbf6774a58e4ff02c2c7341a:refs/remotes/pull/44861/merge
  /usr/lib/git-core/git-remote-https: error while loading shared libraries: /lib/x86_64-linux-gnu/libgssapi_krb5.so.2: invalid ELF header
  The process '/usr/bin/git' failed with exit code 128
  Waiting 16 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +18e82eac24081b13bbf6774a58e4ff02c2c7341a:refs/remotes/pull/44861/merge
  /usr/lib/git-core/git-remote-https: error while loading shared libraries: /lib/x86_64-linux-gnu/libgssapi_krb5.so.2: invalid ELF header
  The process '/usr/bin/git' failed with exit code 128
  Waiting 14 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +18e82eac24081b13bbf6774a58e4ff02c2c7341a:refs/remotes/pull/44861/merge
  /usr/lib/git-core/git-remote-https: error while loading shared libraries: /lib/x86_64-linux-gnu/libgssapi_krb5.so.2: invalid ELF header
  Error: The process '/usr/bin/git' failed with exit code 128
```

**Comment by jmuleiro** [comment]
I'm also seeing this error sporadically. It occurred in one out of 25 identical `ubuntu-20.04` containers created from a matrix strategy.

**Comment by mikhailkoliada** [comment]
I'll check linkage on morning, some ideas crossed my mind

**Comment by mikhailkoliada** [comment]
@Topherhindman @jmuleiro @chris-griffin @yardensade can someone play around for me and if build does not fail for you, run the following command `apt list --installed` (output gonna be long), I suspect there might be dependencies change that caused this, and I wanna study its objdump

**Comment by yardensade** [comment]
> @Topherhindman @jmuleiro @chris-griffin @yardensade can someone play around for me and if build does not fail for you, run the following command `apt list --installed` (output gonna be long), I suspect there might be dependencies change that caused this, and I wanna study its objdump

You mean to `apt list` prior to the checkout step?

**Comment by acaudle10** [comment]
Choose the places in Vietnam for Roger's and Dents

**Comment by acaudle10** [comment]
CAPCAR72 VERSION A-O-last work@$? Neloca

**Comment by mikhailkoliada** [comment]
@yardensade Yep, better even 2 runs to compare, 1 apt list with green checkout and 1 apt list with red checkout (before the actual checkout happens surely), I need to compare some deep dependencies installed in the runner image but I was unable to catch the problem myself.

**Comment by acaudle10** [comment]
Whats the failed exit code issue with #9632.

Is it because the 1=3 for any or all the issues?

Whats the solution for sandbox, jPatdoneD, bandana offenses that allows e
cummin.

To dodge accidents should I run scripts together width.

Or should look forward at resolving the issue without only scripts taking
care of the errors I'm getting from the other 2+.

Also regarding the forbidden detainers at debate alone or should debates be
addressed in scripting?

Please respond now.

**Comment by acaudle10** [comment]
Turning to r script Horton delivery I assume that builders bases are OK?

**Comment by acaudle10** [comment]
I certain the names of the pro pee are withheld in scripts.

**Comment by acaudle10** [comment]
Concerning previous recorded errors which has me mad and hunting for solution with url core duals. I

**Comment by yardensade** [comment]
> @yardensade Yep, better even 2 runs to compare, 1 apt list with green checkout and 1 apt list with red checkout (before the actual checkout happens surely), I need to compare some deep dependencies installed in the runner image but I was unable to catch the problem myself.

I will add it and send here once I get the logs from the broken build as well, should not take too long

**Comment by yardensade** [comment]
Artifact from broken build:
[installed-packages (6).zip](https://github.com/actions/runner-images/files/14896579/installed-packages.6.zip)
@mikhailkoliada

**Comment by mnylensc** [comment]
Maybe related, but also managed to get `invalid ELF header` error from Python installed using `actions/setup-python@v5` running on `ubuntu-latest`:

```
/opt/hostedtoolcache/Python/3.10.14/x64/bin/pip cache dir
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/subprocess.py", line 69, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pip/_internal/cli/main_parser.py", line 5, in <module>
    import subprocess
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/subprocess.py", line 75, in <module>
    import select
ImportError: /opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/lib-dynload/select.cpython-310-x86_64-linux-gnu.so: invalid ELF header

```

**Comment by VinceCarollo** [comment]
FYI: We're currently unable to deploy due to this.

**Comment by erik-bershel** [comment]
Heads up! @mnylensc @yardensade @chris-griffin @jmuleiro @Topherhindman 
May I ask you to check your actions today. New images were rolled out couple hours ago.

**Comment by yardensade** [comment]
So far seems good to me, I will keep monitoring it in the next hours to make sure it is stable. (I moved to ubuntu 22 tho, which had a docker error but since your new version seems to be solved)

**Comment by acaudle10** [comment]
What do you think I should do about the docker, error, GINA, retire, cash,
Irs, referencing any related to cv-00650, cv-00905, and or cv-0096 as just
referencing numbers to knowledge and agreements, because they cant tell me
anything outside of those numbers in meetings. Any information will help.
I'm thinking about coding the conspired to share my records and
intellectual property, domain, and storage and comprised it by cyber
related attacks. Any thoughts? In hopes of discovery 1 take care of 3 or
more.

**Comment by acaudle10** [comment]
Absolutely. What would you like to see?

**Comment by acaudle10** [comment]
What happens at checkou

**Comment by mnylensc** [comment]
@erik-bershel thank you. Will monitor if this happens. If possible, is there an explanation of what could've caused this, if you think it's now fixed?

**Comment by erik-bershel** [comment]
Heads up!
Seems that the deployment resolved the issue - we see no new cases during last days. 

Unfortunately, we cannot provide details of what happened at this time. If and when such an opportunity arises, we will publish this information here with a mention of those interested. We are now focused on developing tests that will allow us to catch similar problems at an earlier stage in the future.

**Comment by magnesj** [comment]
The error message  `Error: The process '/usr/bin/git' failed with exit code 128` is appearing for all my jobs now.
https://github.com/OPM/ResInsight/actions/runs/11659140848/job/32459722712

**Comment by alelom** [comment]
> The error message Error: The process '/usr/bin/git' failed with exit code 128 is appearing for all my jobs now.
https://github.com/OPM/ResInsight/actions/runs/11659140848/job/32459722712

same here.

**Comment by AmandineScopely** [comment]
That same error happened to me yesterday with the action `actions/checkout@v3` and ubuntu-latest.
Here are the logs:
```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  remote: Internal Server Error
  Error: fatal: unable to access 'https://github.com/xxx/xxx/': The requested URL returned error: 500
  The process '/usr/bin/git' failed with exit code 128
  Waiting 16 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  remote: Internal Server Error
  Error: fatal: unable to access 'https://github.com/xxx/xxx/': The requested URL returned error: 500
  The process '/usr/bin/git' failed with exit code 128
  Waiting 10 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
  remote: Internal Server Error
  Error: fatal: unable to access 'https://github.com/xxx/xxx/': The requested URL returned error: 500
  Error: The process '/usr/bin/git' failed with exit code 128
```

**Comment by erik-bershel** [comment]
Hey @AmandineScopely!

>   Error: fatal: unable to access 'https://github.com/xxx/xxx/': The requested URL returned error: 500

That's the real issue. GitHub was struggling during the workflow run: https://www.githubstatus.com/incidents/5q7nmlxz30sk

> That same error happened to me yesterday with the action actions/checkout@v3 and ubuntu-latest.

Not related to the failure. Let me recommend you to update checkout version to one of the currently supported which is v5 and v4.

**Comment by ykla** [comment]
see also https://github.com/actions/checkout/issues/417
